// SPDX-License-Identifier: GPL-2.0-or-later
// Copyright (C) 2026 Tiflo.Info

static UINT QtVirtualKey(QKeyEvent *event){
    UINT key=static_cast<UINT>(event->nativeVirtualKey());if(key)return key;int qtKey=event->key();
    if(qtKey>=Qt::Key_A&&qtKey<=Qt::Key_Z)return static_cast<UINT>('A'+qtKey-Qt::Key_A);
    if(qtKey>=Qt::Key_0&&qtKey<=Qt::Key_9)return static_cast<UINT>('0'+qtKey-Qt::Key_0);
    if(qtKey>=Qt::Key_F1&&qtKey<=Qt::Key_F24)return static_cast<UINT>(VK_F1+qtKey-Qt::Key_F1);
    switch(qtKey){case Qt::Key_Space:return VK_SPACE;case Qt::Key_Backspace:return VK_BACK;case Qt::Key_Delete:return VK_DELETE;case Qt::Key_Insert:return VK_INSERT;case Qt::Key_Home:return VK_HOME;case Qt::Key_End:return VK_END;case Qt::Key_PageUp:return VK_PRIOR;case Qt::Key_PageDown:return VK_NEXT;case Qt::Key_Left:return VK_LEFT;case Qt::Key_Right:return VK_RIGHT;case Qt::Key_Up:return VK_UP;case Qt::Key_Down:return VK_DOWN;case Qt::Key_Pause:return VK_PAUSE;case Qt::Key_Print:return VK_SNAPSHOT;default:return 0;}
}

class QtShortcutCaptureEdit final:public QLineEdit{
public:
    std::function<void(key_combo)> captured;
    std::function<void(const QString&)> rejected;
    std::function<void()> acceptRequested;
    explicit QtShortcutCaptureEdit(QWidget *parent=nullptr):QLineEdit(parent){setReadOnly(true);setAccessibleName(LText(LocalText::Shortcut));setAccessibleDescription(LText(LocalText::ShortcutInstructions));}
protected:
    void keyPressEvent(QKeyEvent *event) override{
        if(event->key()==Qt::Key_Return||event->key()==Qt::Key_Enter){if(acceptRequested)acceptRequested();event->accept();return;}if(event->key()==Qt::Key_Tab||event->key()==Qt::Key_Backtab||event->key()==Qt::Key_Escape){QLineEdit::keyPressEvent(event);return;}
        UINT key=QtVirtualKey(event);Qt::KeyboardModifiers modifiers=event->modifiers();bool ctrl=modifiers.testFlag(Qt::ControlModifier),alt=modifiers.testFlag(Qt::AltModifier),shift=modifiers.testFlag(Qt::ShiftModifier),win=modifiers.testFlag(Qt::MetaModifier);if(!key){if(rejected)rejected(LText(LocalText::KeyCannotAssign));QApplication::beep();event->accept();return;}if(ReservedShortcut(key,ctrl,alt,shift,win)){if(rejected)rejected(LText(LocalText::ReservedShortcut));QApplication::beep();event->accept();return;}int obsKey=ObsKeyFromVirtualKey(key);if(obsKey<=0){if(rejected)rejected(LText(LocalText::ObsUnknownKey));QApplication::beep();event->accept();return;}key_combo combo{(ctrl?OBS_MOD_CONTROL:0u)|(alt?OBS_MOD_ALT:0u)|(shift?OBS_MOD_SHIFT:0u),obsKey};if(captured)captured(combo);event->accept();
    }
};

class QtHotkeyAssignmentDialog final:public QDialog{
    size_t index{};std::vector<key_combo> bindings,originalBindings;QListWidget *assignments{};QtShortcutCaptureEdit *capture{};QPushButton *removeButton{};QLabel *status{};bool append{},armed{true};
    void setStatus(const QString &message){if(status->text()!=message)status->setText(message);}
    void announce(const QString &message){setStatus(message);QAccessibleAnnouncementEvent event(this,message);event.setPoliteness(QAccessible::AnnouncementPoliteness::Assertive);QAccessible::updateAccessibility(&event);}
    void updateControls(){removeButton->setEnabled(assignments->currentRow()>=0&&!bindings.empty());}
    void refresh(){int selected=assignments->currentRow();QSignalBlocker blocker(assignments);assignments->clear();for(key_combo combo:bindings)assignments->addItem(QString::fromStdWString(ComboText(combo)));if(!bindings.empty()){selected=std::clamp(selected,0,static_cast<int>(bindings.size())-1);assignments->setCurrentRow(selected);if(!append)capture->setText(QString::fromStdWString(ComboText(bindings[static_cast<size_t>(selected)])));}else capture->setText(LText(LocalText::None));updateControls();}
    void receive(key_combo combo){if(!armed){announce(LText(LocalText::ChooseAssignmentFirst));QApplication::beep();return;}if(std::any_of(bindings.begin(),bindings.end(),[&](key_combo existing){return CombosEqual(existing,combo); })){announce(LText(LocalText::DuplicateAssignment));QApplication::beep();return;}int selected=assignments->currentRow();QString text=QString::fromStdWString(ComboText(combo));if(append||selected<0){bindings.push_back(combo);assignments->addItem(text);assignments->setCurrentRow(assignments->count()-1);}else{bindings[static_cast<size_t>(selected)]=combo;assignments->item(selected)->setText(text);}append=false;armed=false;capture->setText(text);setStatus(LText(LocalText::ShortcutCaptured).arg(text));updateControls();}
    void tryAccept(){
        struct Conflict{key_combo combo;size_t otherIndex;};std::vector<Conflict> conflicts;auto distinct=DistinctCommandIndices();
        for(key_combo combo:bindings){bool newlyAssigned=std::none_of(originalBindings.begin(),originalBindings.end(),[&](key_combo original){return CombosEqual(original,combo);});if(!newlyAssigned)continue;for(size_t otherIndex=0;otherIndex<hotkeys.size();++otherIndex){if(otherIndex==index||SameLogicalCommand(hotkeys[index],hotkeys[otherIndex]))continue;bool assigned=std::any_of(hotkeys[otherIndex].bindings.begin(),hotkeys[otherIndex].bindings.end(),[&](key_combo candidate){return CombosEqual(candidate,combo);});if(!assigned)continue;bool alreadyListed=std::any_of(conflicts.begin(),conflicts.end(),[&](const Conflict &existing){return CombosEqual(existing.combo,combo)&&SameLogicalCommand(hotkeys[existing.otherIndex],hotkeys[otherIndex]);});if(!alreadyListed)conflicts.push_back({combo,otherIndex});}}
        for(const Conflict &conflict:conflicts){QString shortcut=QString::fromStdWString(ComboText(conflict.combo)),command=QString::fromStdWString(CommandDisplayLabel(conflict.otherIndex,distinct));QMessageBox box(QMessageBox::Warning,QString::fromWCharArray(Tr(UiText::ConflictTitle)),LText(LocalText::ReassignConflictMessage).arg(shortcut,command),QMessageBox::NoButton,this);QPushButton *yes=box.addButton(LText(LocalText::Yes),QMessageBox::AcceptRole);QPushButton *no=box.addButton(LText(LocalText::No),QMessageBox::RejectRole);box.setDefaultButton(no);box.setEscapeButton(no);box.exec();if(box.clickedButton()!=yes){capture->setFocus(Qt::OtherFocusReason);return;}}
        for(key_combo combo:bindings){bool newlyAssigned=std::none_of(originalBindings.begin(),originalBindings.end(),[&](key_combo original){return CombosEqual(original,combo);});if(!newlyAssigned)continue;for(size_t otherIndex=0;otherIndex<hotkeys.size();++otherIndex){if(otherIndex==index||SameLogicalCommand(hotkeys[index],hotkeys[otherIndex]))continue;auto &otherBindings=hotkeys[otherIndex].bindings;otherBindings.erase(std::remove_if(otherBindings.begin(),otherBindings.end(),[&](key_combo candidate){return CombosEqual(candidate,combo);}),otherBindings.end());}}
        hotkeys[index].bindings=bindings;accept();
    }
public:
    QtHotkeyAssignmentDialog(size_t hotkeyIndex,QWidget *parent):QDialog(parent),index(hotkeyIndex),bindings(hotkeys[hotkeyIndex].bindings),originalBindings(bindings){
        setWindowTitle(LText(LocalText::HotKey));setWindowModality(Qt::WindowModal);auto *layout=new QVBoxLayout(this);auto distinct=DistinctCommandIndices();QString commandText=QString::fromStdWString(CommandDisplayLabel(index,distinct));auto *command=new QLabel(LText(LocalText::CommandFormat).arg(commandText),this);command->setWordWrap(true);command->setAccessibleName(QStringLiteral(" "));command->setAccessibleDescription(QStringLiteral(" "));layout->addWidget(command);auto *assignedLabel=new QLabel(QStringLiteral("&")+LText(LocalText::AssignedShortcuts)+QStringLiteral(":"),this);assignments=new QListWidget(this);assignments->setAccessibleName(LText(LocalText::AssignedShortcuts));assignments->setAccessibleDescription(LText(LocalText::AssignmentListHelp));assignments->setTabKeyNavigation(false);assignedLabel->setBuddy(assignments);layout->addWidget(assignedLabel);layout->addWidget(assignments);
        auto *captureLabel=new QLabel(LText(LocalText::ShortcutLabel),this);capture=new QtShortcutCaptureEdit(this);capture->setAccessibleDescription(LText(LocalText::CommandCaptureHelp).arg(commandText));captureLabel->setBuddy(capture);layout->addWidget(captureLabel);layout->addWidget(capture);status=new QLabel(this);status->setWordWrap(true);status->setAccessibleName(QStringLiteral(" "));status->setAccessibleDescription(QStringLiteral(" "));layout->addWidget(status);auto *bindingButtons=new QHBoxLayout;auto *addAnother=new QPushButton(LText(LocalText::AddAnotherShortcut),this);removeButton=new QPushButton(LText(LocalText::RemoveShortcut),this);bindingButtons->addWidget(addAnother);bindingButtons->addWidget(removeButton);bindingButtons->addStretch();layout->addLayout(bindingButtons);auto *buttons=new QDialogButtonBox(QDialogButtonBox::Ok|QDialogButtonBox::Cancel,this);layout->addWidget(buttons);QPushButton *ok=buttons->button(QDialogButtonBox::Ok),*cancel=buttons->button(QDialogButtonBox::Cancel);ok->setText(LText(LocalText::Ok));cancel->setText(LText(LocalText::Cancel));QWidget::setTabOrder(assignments,capture);QWidget::setTabOrder(capture,addAnother);QWidget::setTabOrder(addAnother,removeButton);QWidget::setTabOrder(removeButton,ok);QWidget::setTabOrder(ok,cancel);
        capture->captured=[this](key_combo combo){receive(combo);};capture->rejected=[this](const QString &message){announce(message);};capture->acceptRequested=[this]{tryAccept();};QObject::connect(assignments,&QListWidget::currentRowChanged,[this](int row){if(row>=0&&row<static_cast<int>(bindings.size())){append=false;armed=true;capture->setText(QString::fromStdWString(ComboText(bindings[static_cast<size_t>(row)])));}updateControls();});QObject::connect(addAnother,&QPushButton::clicked,[this]{append=true;armed=true;capture->setText(LText(LocalText::None));setStatus(QString());capture->setFocus(Qt::OtherFocusReason);});QObject::connect(removeButton,&QPushButton::clicked,[this]{int selected=assignments->currentRow();if(selected<0||selected>=static_cast<int>(bindings.size())){announce(LText(LocalText::SelectShortcutToRemove));QApplication::beep();return;}QString removed=assignments->item(selected)->text();bindings.erase(bindings.begin()+selected);delete assignments->takeItem(selected);append=bindings.empty();armed=true;if(!bindings.empty()){int next=std::min(selected,static_cast<int>(bindings.size())-1);assignments->setCurrentRow(next);assignments->setFocus(Qt::OtherFocusReason);setStatus(LText(LocalText::RemovedShortcut).arg(removed));}else{capture->setText(LText(LocalText::None));capture->setFocus(Qt::OtherFocusReason);announce(LText(LocalText::RemovedShortcut).arg(removed));}updateControls();});QObject::connect(buttons,&QDialogButtonBox::accepted,[this]{tryAccept();});QObject::connect(buttons,&QDialogButtonBox::rejected,this,&QDialog::reject);refresh();resize(600,450);capture->setFocus(Qt::OtherFocusReason);
    }
};

static constexpr int COMMAND_TEXT_ROLE=Qt::UserRole+1,SHORTCUT_TEXT_ROLE=Qt::UserRole+2;

class QtHotkeyListDelegate final:public QStyledItemDelegate{
public:
    using QStyledItemDelegate::QStyledItemDelegate;
    void paint(QPainter *painter,const QStyleOptionViewItem &option,const QModelIndex &index) const override{
        QStyleOptionViewItem background(option);initStyleOption(&background,index);background.text.clear();QStyledItemDelegate::paint(painter,background,index);QRect content=option.rect.adjusted(8,0,-8,0);int shortcutWidth=std::clamp(content.width()/3,180,360);QRect commandRect=content;commandRect.setRight(content.right()-shortcutWidth-12);QRect shortcutRect=content;shortcutRect.setLeft(commandRect.right()+13);QColor color=(option.state&QStyle::State_Selected)?option.palette.color(QPalette::HighlightedText):option.palette.color(QPalette::Text);painter->save();painter->setPen(color);QString command=option.fontMetrics.elidedText(index.data(COMMAND_TEXT_ROLE).toString(),Qt::ElideRight,commandRect.width());QString shortcut=option.fontMetrics.elidedText(index.data(SHORTCUT_TEXT_ROLE).toString(),Qt::ElideLeft,shortcutRect.width());painter->drawText(commandRect,Qt::AlignVCenter|Qt::AlignLeft,command);painter->drawText(shortcutRect,Qt::AlignVCenter|Qt::AlignRight,shortcut);painter->restore();
    }
};

class QtCommandList final:public QListWidget{
public:
    std::function<void()> editRequested,removeRequested,closeRequested;
    using QListWidget::QListWidget;
protected:
    void keyPressEvent(QKeyEvent *event) override{if(event->key()==Qt::Key_Return||event->key()==Qt::Key_Enter){if(editRequested)editRequested();event->accept();return;}if(event->key()==Qt::Key_Delete){if(removeRequested)removeRequested();event->accept();return;}if(event->key()==Qt::Key_Escape){if(closeRequested)closeRequested();event->accept();return;}QListWidget::keyPressEvent(event);}
};

class PreFaderStopListWidget final:public QListWidget{
public:
    std::function<void()> removeRequested;
    using QListWidget::QListWidget;
protected:
    void keyPressEvent(QKeyEvent *event) override{if(event->key()==Qt::Key_Delete){if(removeRequested)removeRequested();event->accept();return;}QListWidget::keyPressEvent(event);}
};

class AdvancedSoundSettingsDialog final:public QDialog{
    QListWidget *navigation_{};QStackedWidget *pages_{};QDoubleSpinBox *warningLevel_{},*warningTime_{},*peakMargin_{},*maximumReduction_{},*compressionSpread_{},*limiterCeiling_{};QComboBox *maximumRatio_{},*limiterSources_{};PreFaderStopListWidget *stopList_{};QPushButton *removeStoppedSource_{},*apply_{};QLabel *emptyStopList_{};QJsonArray stoppedSources_;bool changed_{};
    static void Configure(QDoubleSpinBox *control,double minimum,double maximum,double step,const QString &suffix,const QString &name,const QString &description){
        control->setRange(minimum,maximum);control->setDecimals(1);control->setSingleStep(step);control->setSuffix(suffix);control->setKeyboardTracking(false);control->setAccessibleName(name);control->setAccessibleDescription(description);
    }
    static QLabel *AddRow(QFormLayout *form,LocalText text,QWidget *control,QWidget *parent){auto *label=new QLabel(LText(text)+QStringLiteral(":"),parent);label->setBuddy(control);form->addRow(label,control);return label;}
    void MarkChanged(){changed_=true;if(apply_)apply_->setEnabled(true);}
    void UpdateStopListControls(){bool empty=stopList_->count()==0;emptyStopList_->setVisible(empty);removeStoppedSource_->setEnabled(stopList_->currentRow()>=0);}
    void RemoveStoppedSource(){int row=stopList_->currentRow();if(row<0||row>=stoppedSources_.size()){QApplication::beep();return;}stoppedSources_.removeAt(row);delete stopList_->takeItem(row);if(stopList_->count()>0)stopList_->setCurrentRow(std::min(row,stopList_->count()-1));UpdateStopListControls();MarkChanged();}
    bool ConfirmRestoreDefaults(const QString &message){
        QMessageBox box(QMessageBox::Question,QStringLiteral("Accessible Studio"),message,QMessageBox::NoButton,this);QPushButton *yes=box.addButton(LText(LocalText::Yes),QMessageBox::YesRole);QPushButton *no=box.addButton(LText(LocalText::No),QMessageBox::NoRole);box.setDefaultButton(yes);box.setEscapeButton(no);box.exec();return box.clickedButton()==yes;
    }
    void RestoreAudibleMeterDefaults(){
        if(!ConfirmRestoreDefaults(LText(LocalText::RestoreAudibleMeterDefaultsQuestion)))return;
        warningLevel_->setValue(AudibleMeterDefaultOutputWarningDb());warningTime_->setValue(1.5);peakMargin_->setValue(3.0);maximumReduction_->setValue(12.0);stoppedSources_=QJsonArray();stopList_->clear();UpdateStopListControls();MarkChanged();
    }
    void RestoreSoundDoctorDefaults(){
        if(!ConfirmRestoreDefaults(LText(LocalText::RestoreSoundDoctorDefaultsQuestion)))return;
        compressionSpread_->setValue(8.0);maximumRatio_->setCurrentIndex(maximumRatio_->findData(3.0));limiterSources_->setCurrentIndex(0);limiterCeiling_->setValue(-3.0);MarkChanged();
    }
    bool SaveAll(){
        if(!SaveAudibleMeterSettings(warningLevel_->value(),warningTime_->value(),peakMargin_->value(),maximumReduction_->value())){QMessageBox::critical(this,QStringLiteral("Accessible Studio"),LText(LocalText::AudibleMeterSettingsSaveFailure));return false;}
        if(!SaveAudibleMeterInputStopList(stoppedSources_)){QMessageBox::critical(this,QStringLiteral("Accessible Studio"),LText(LocalText::StopListSaveFailure));return false;}
        if(!SaveSoundDoctorSettings(compressionSpread_->value(),maximumRatio_->currentData().toDouble(),limiterSources_->currentData().toBool(),limiterCeiling_->value())){QMessageBox::critical(this,QStringLiteral("Accessible Studio"),LText(LocalText::SoundDoctorSettingsSaveFailure));return false;}
        changed_=false;apply_->setEnabled(false);return true;
    }
public:
    explicit AdvancedSoundSettingsDialog(QWidget *parent):QDialog(parent){
        QString title=LText(LocalText::AdvancedSoundSettings);title.remove(QChar(0x2026));setWindowTitle(title);setWindowModality(Qt::WindowModal);setMinimumSize(700,512);setSizeGripEnabled(true);auto *layout=new QVBoxLayout(this);auto *content=new QHBoxLayout;content->setSpacing(0);navigation_=new QListWidget(this);navigation_->setSizePolicy(QSizePolicy::Minimum,QSizePolicy::Expanding);navigation_->setMaximumWidth(180);navigation_->setIconSize(QSize(16,16));navigation_->setSpacing(1);navigation_->addItem(LText(LocalText::AudibleMeterMenu));navigation_->addItem(LText(LocalText::SoundDoctorMenu));content->addWidget(navigation_);pages_=new QStackedWidget(this);content->addWidget(pages_,1);layout->addLayout(content,1);

        auto *audiblePage=new QWidget(pages_);auto *audibleLayout=new QVBoxLayout(audiblePage);audibleLayout->setContentsMargins(9,0,0,0);auto *form=new QFormLayout;
        warningLevel_=new QDoubleSpinBox(this);Configure(warningLevel_,-30.0,0.0,0.5,QStringLiteral(" dBFS"),LText(LocalText::OutputWarningLevel),LText(LocalText::OutputWarningLevelDescription));warningLevel_->setValue(AudibleMeterOutputWarningDb());
        warningTime_=new QDoubleSpinBox(this);Configure(warningTime_,0.1,30.0,0.1,QStringLiteral(" s"),LText(LocalText::TimeAboveWarningLevel),LText(LocalText::TimeAboveWarningLevelDescription));warningTime_->setValue(AudibleMeterWarningSeconds());
        peakMargin_=new QDoubleSpinBox(this);Configure(peakMargin_,0.0,12.0,0.5,QStringLiteral(" dB"),LText(LocalText::PeakSafetyMargin),LText(LocalText::PeakSafetyMarginDescription));peakMargin_->setValue(AudibleMeterPeakSafetyMarginDb());
        maximumReduction_=new QDoubleSpinBox(this);Configure(maximumReduction_,0.5,30.0,0.5,QStringLiteral(" dB"),LText(LocalText::MaximumAutomaticReduction),LText(LocalText::MaximumAutomaticReductionDescription));maximumReduction_->setValue(AudibleMeterMaximumReductionDb());
        AddRow(form,LocalText::OutputWarningLevel,warningLevel_,audiblePage);AddRow(form,LocalText::TimeAboveWarningLevel,warningTime_,audiblePage);AddRow(form,LocalText::PeakSafetyMargin,peakMargin_,audiblePage);AddRow(form,LocalText::MaximumAutomaticReduction,maximumReduction_,audiblePage);audibleLayout->addLayout(form);
        auto *stopGroup=new QGroupBox(LText(LocalText::PreFaderStopList),audiblePage);auto *stopLayout=new QVBoxLayout(stopGroup);auto *description=new QLabel(LText(LocalText::PreFaderStopListDescription),stopGroup);description->setWordWrap(true);description->setAccessibleName(QStringLiteral(" "));stopLayout->addWidget(description);stopList_=new PreFaderStopListWidget(stopGroup);stopList_->setAccessibleName(LText(LocalText::PreFaderStopList));stopList_->setAccessibleDescription(LText(LocalText::PreFaderStopListDescription));stopList_->setSelectionMode(QAbstractItemView::SingleSelection);stoppedSources_=AudibleMeterInputStopList();for(const QJsonValue &value:stoppedSources_){QString name=value.toObject().value(QStringLiteral("name")).toString();stopList_->addItem(name.isEmpty()?LText(LocalText::AudioSource):name);}stopLayout->addWidget(stopList_);emptyStopList_=new QLabel(LText(LocalText::NoPreFaderStoppedSources),stopGroup);emptyStopList_->setWordWrap(true);stopLayout->addWidget(emptyStopList_);removeStoppedSource_=new QPushButton(LText(LocalText::RemoveFromStopList),stopGroup);stopLayout->addWidget(removeStoppedSource_);
        audibleLayout->addWidget(stopGroup);auto *restoreAudibleDefaults=new QPushButton(LText(LocalText::RestoreDefaults),audiblePage);audibleLayout->addWidget(restoreAudibleDefaults,0,Qt::AlignLeft);pages_->addWidget(audiblePage);

        auto *doctorPage=new QWidget(pages_);auto *doctorLayout=new QVBoxLayout(doctorPage);doctorLayout->setContentsMargins(9,0,0,0);auto *doctorForm=new QFormLayout;compressionSpread_=new QDoubleSpinBox(doctorPage);Configure(compressionSpread_,6.0,15.0,0.5,QStringLiteral(" dB"),LText(LocalText::MinimumCompressionSpread),LText(LocalText::MinimumCompressionSpreadDescription));compressionSpread_->setValue(SoundDoctorMinimumCompressionSpreadDb());AddRow(doctorForm,LocalText::MinimumCompressionSpread,compressionSpread_,doctorPage);
        maximumRatio_=new QComboBox(doctorPage);maximumRatio_->setAccessibleName(LText(LocalText::MaximumCompressionRatio));maximumRatio_->setAccessibleDescription(LText(LocalText::MaximumCompressionRatioDescription));maximumRatio_->addItem(QStringLiteral("2.5:1"),2.5);maximumRatio_->addItem(QStringLiteral("3:1"),3.0);maximumRatio_->addItem(QStringLiteral("3.5:1"),3.5);maximumRatio_->setCurrentIndex(std::max(0,maximumRatio_->findData(SoundDoctorMaximumCompressionRatio())));AddRow(doctorForm,LocalText::MaximumCompressionRatio,maximumRatio_,doctorPage);
        limiterSources_=new QComboBox(doctorPage);limiterSources_->setAccessibleName(LText(LocalText::LimiterRecommendationSources));limiterSources_->setAccessibleDescription(LText(LocalText::LimiterRecommendationSourcesDescription));limiterSources_->addItem(LText(LocalText::LikelyLiveInputs),false);limiterSources_->addItem(LText(LocalText::AllActiveAudioSources),true);limiterSources_->setCurrentIndex(SoundDoctorLimiterAllActiveSources()?1:0);AddRow(doctorForm,LocalText::LimiterRecommendationSources,limiterSources_,doctorPage);
        limiterCeiling_=new QDoubleSpinBox(doctorPage);Configure(limiterCeiling_,-12.0,-1.0,0.5,QStringLiteral(" dBFS"),LText(LocalText::RecommendedLimiterCeiling),LText(LocalText::RecommendedLimiterCeilingDescription));limiterCeiling_->setValue(SoundDoctorLimiterThresholdDb());AddRow(doctorForm,LocalText::RecommendedLimiterCeiling,limiterCeiling_,doctorPage);doctorLayout->addLayout(doctorForm);auto *restoreSoundDoctorDefaults=new QPushButton(LText(LocalText::RestoreDefaults),doctorPage);doctorLayout->addWidget(restoreSoundDoctorDefaults,0,Qt::AlignLeft);doctorLayout->addStretch(1);pages_->addWidget(doctorPage);

        auto *buttons=new QDialogButtonBox(QDialogButtonBox::Apply|QDialogButtonBox::Cancel|QDialogButtonBox::Ok,this);apply_=buttons->button(QDialogButtonBox::Apply);apply_->setEnabled(false);layout->addWidget(buttons);navigation_->setCurrentRow(0);pages_->setCurrentIndex(0);
        QObject::connect(navigation_,&QListWidget::currentRowChanged,pages_,&QStackedWidget::setCurrentIndex);stopList_->removeRequested=[this]{RemoveStoppedSource();};QObject::connect(stopList_,&QListWidget::currentRowChanged,this,[this]{UpdateStopListControls();});QObject::connect(removeStoppedSource_,&QPushButton::clicked,this,[this]{RemoveStoppedSource();});QObject::connect(restoreAudibleDefaults,&QPushButton::clicked,this,[this]{RestoreAudibleMeterDefaults();});QObject::connect(restoreSoundDoctorDefaults,&QPushButton::clicked,this,[this]{RestoreSoundDoctorDefaults();});
        for(QDoubleSpinBox *control:{warningLevel_,warningTime_,peakMargin_,maximumReduction_,compressionSpread_,limiterCeiling_})QObject::connect(control,&QDoubleSpinBox::valueChanged,this,[this]{MarkChanged();});QObject::connect(maximumRatio_,&QComboBox::currentIndexChanged,this,[this]{MarkChanged();});QObject::connect(limiterSources_,&QComboBox::currentIndexChanged,this,[this]{MarkChanged();});QObject::connect(apply_,&QPushButton::clicked,this,[this]{SaveAll();});QObject::connect(buttons->button(QDialogButtonBox::Ok),&QPushButton::clicked,this,[this]{if(!changed_||SaveAll())accept();});QObject::connect(buttons->button(QDialogButtonBox::Cancel),&QPushButton::clicked,this,&QDialog::reject);UpdateStopListControls();resize(981,730);navigation_->setFocus(Qt::OtherFocusReason);
    }
};

static void ShowAdvancedSoundSettings(){
    QWidget *parent=QApplication::activeWindow();if(!parent)parent=obsMainWindow;AdvancedSoundSettingsDialog dialog(parent);dialog.exec();
}

class QtHotkeyEditorDialog final:public QDialog{
    QLineEdit *search{};QtCommandList *commands{};QCheckBox *allowObsHotkeyControl{};QPushButton *editButton{},*removeButton{};QLabel *status{};bool closing{},originalAllowObsHotkeyControl{};uint64_t editingGeneration{obsEditingGeneration};config *editingProfile{api.profile_config()};
    int selectedIndex() const{QListWidgetItem *item=commands->currentItem();return item?item->data(Qt::UserRole).toInt():-1;}
    void setStatus(const QString &message){if(status->text()!=message)status->setText(message);}
    void announce(const QString &message){setStatus(message);QAccessibleAnnouncementEvent event(this,message);event.setPoliteness(QAccessible::AnnouncementPoliteness::Assertive);QAccessible::updateAccessibility(&event);}
    void updateButtons(){int selected=selectedIndex();editButton->setEnabled(selected>=0);removeButton->setEnabled(selected>=0&&!hotkeys[static_cast<size_t>(selected)].bindings.empty());}
    void refresh(int preferred=-1){QString needle=search->text();auto distinct=DistinctCommandIndices();QSignalBlocker blocker(commands);commands->clear();QListWidgetItem *preferredItem=nullptr;for(size_t i:distinct){QString command=QString::fromStdWString(CommandDisplayLabel(i,distinct));QString context=QString::fromUtf8(hotkeys[i].context.c_str());if(!needle.isEmpty()&&!command.contains(needle,Qt::CaseInsensitive)&&!context.contains(needle,Qt::CaseInsensitive))continue;QString shortcut=QString::fromStdWString(BindingSummary(hotkeys[i]));auto *item=new QListWidgetItem(LText(LocalText::CommandListItem).arg(command,shortcut),commands);item->setData(Qt::UserRole,static_cast<int>(i));item->setData(COMMAND_TEXT_ROLE,command);item->setData(SHORTCUT_TEXT_ROLE,shortcut);if(static_cast<int>(i)==preferred)preferredItem=item;}if(preferredItem)commands->setCurrentItem(preferredItem);else if(commands->count()>0)commands->setCurrentRow(0);updateButtons();setStatus(LText(LocalText::CommandsShown).arg(commands->count()));}
    void updateVisibleItems(){for(int row=0;row<commands->count();++row){QListWidgetItem *item=commands->item(row);int hotkeyIndex=item->data(Qt::UserRole).toInt();QString command=item->data(COMMAND_TEXT_ROLE).toString(),shortcut=QString::fromStdWString(BindingSummary(hotkeys[static_cast<size_t>(hotkeyIndex)]));item->setText(LText(LocalText::CommandListItem).arg(command,shortcut));item->setData(SHORTCUT_TEXT_ROLE,shortcut);}commands->viewport()->update();updateButtons();}
    void updateCurrentItem(){QListWidgetItem *item=commands->currentItem();int selected=selectedIndex();if(!item||selected<0)return;QString command=item->data(COMMAND_TEXT_ROLE).toString(),shortcut=QString::fromStdWString(BindingSummary(hotkeys[static_cast<size_t>(selected)]));item->setText(LText(LocalText::CommandListItem).arg(command,shortcut));item->setData(SHORTCUT_TEXT_ROLE,shortcut);commands->viewport()->update();updateButtons();}
    void editSelected(){int selected=selectedIndex();if(selected<0){QApplication::beep();return;}QtHotkeyAssignmentDialog dialog(static_cast<size_t>(selected),this);if(dialog.exec()==QDialog::Accepted)updateVisibleItems();}
    void removeSelected(){int selected=selectedIndex();if(selected<0){QApplication::beep();return;}if(hotkeys[static_cast<size_t>(selected)].bindings.empty()){announce(LText(LocalText::NoShortcutsToRemove));QApplication::beep();return;}QString command=commands->currentItem()->data(COMMAND_TEXT_ROLE).toString();hotkeys[static_cast<size_t>(selected)].bindings.clear();updateCurrentItem();setStatus(LText(LocalText::RemovedAllShortcuts).arg(command));}
    bool dirty() const{return EditorDirty()||allowObsHotkeyControl->isChecked()!=originalAllowObsHotkeyControl;}
    bool saveAll(){if(editingGeneration!=obsEditingGeneration||editingProfile!=api.profile_config()||!ValidateEditorBindings()){QMessageBox::warning(this,QStringLiteral("Accessible Studio"),ReliabilityText::StaleEditor());return false;}if(SaveEditorChanges(this)!=EditorSaveResult::Saved)return false;bool allow=allowObsHotkeyControl->isChecked();if(allow!=originalAllowObsHotkeyControl&&!SaveObsHotkeyManagementPreference(allow)){QMessageBox::critical(this,QStringLiteral("Accessible Studio"),LText(LocalText::HotkeyPolicySaveFailure));return false;}originalAllowObsHotkeyControl=allow;return true;}
    void discard(){for(Hotkey &hotkey:hotkeys)hotkey.bindings=hotkey.originalBindings;allowObsHotkeyControl->setChecked(originalAllowObsHotkeyControl);}
protected:
    void closeEvent(QCloseEvent *event) override{
        if(closing||!dirty()){event->accept();return;}QMessageBox box(QMessageBox::Question,QStringLiteral("Accessible Studio"),LText(LocalText::UnsavedChanges),QMessageBox::Save|QMessageBox::Discard|QMessageBox::Cancel,this);box.setInformativeText(LText(LocalText::UnsavedDetail));box.button(QMessageBox::Save)->setText(LText(LocalText::Save));box.button(QMessageBox::Discard)->setText(LText(LocalText::Discard));box.button(QMessageBox::Cancel)->setText(LText(LocalText::Cancel));box.setDefaultButton(QMessageBox::Save);int choice=box.exec();if(choice==QMessageBox::Save){if(saveAll()){closing=true;event->accept();}else event->ignore();}else if(choice==QMessageBox::Discard){discard();closing=true;event->accept();}else event->ignore();
    }
    void reject() override{close();}
public:
    explicit QtHotkeyEditorDialog(QWidget *parent):QDialog(parent){
        setWindowTitle(QStringLiteral("Accessible Studio — ")+LText(LocalText::ShortcutEditor));setAttribute(Qt::WA_DeleteOnClose);setWindowModality(Qt::WindowModal);
        auto *layout=new QVBoxLayout(this);auto *searchLabel=new QLabel(LText(LocalText::FindCommands),this);search=new QLineEdit(this);search->setAccessibleName(LAccessibleLabel(LocalText::FindCommands));searchLabel->setBuddy(search);layout->addWidget(searchLabel);layout->addWidget(search);
        auto *headers=new QHBoxLayout;auto *commandHeader=new QLabel(LText(LocalText::Command),this);auto *shortcutHeader=new QLabel(LText(LocalText::AssignedShortcuts),this);shortcutHeader->setAlignment(Qt::AlignRight);headers->addWidget(commandHeader,2);headers->addWidget(shortcutHeader,1);layout->addLayout(headers);
        commands=new QtCommandList(this);commands->setItemDelegate(new QtHotkeyListDelegate(commands));commands->setAccessibleName(LText(LocalText::Commands));commands->setAccessibleDescription(LText(LocalText::CommandListHelp));commands->setSelectionMode(QAbstractItemView::SingleSelection);commands->setEditTriggers(QAbstractItemView::NoEditTriggers);commands->setTabKeyNavigation(false);layout->addWidget(commands);
        status=new QLabel(this);status->setWordWrap(true);status->setAccessibleName(QStringLiteral(" "));status->setAccessibleDescription(QStringLiteral(" "));layout->addWidget(status);allowObsHotkeyControl=new QCheckBox(LText(LocalText::AllowObsManageHotkeys),this);originalAllowObsHotkeyControl=AllowObsToManageHotkeysOutsideObs();allowObsHotkeyControl->setChecked(originalAllowObsHotkeyControl);layout->addWidget(allowObsHotkeyControl);auto *buttons=new QDialogButtonBox(this);editButton=buttons->addButton(LText(LocalText::AddOrEdit),QDialogButtonBox::ActionRole);removeButton=buttons->addButton(LText(LocalText::RemoveShortcut),QDialogButtonBox::DestructiveRole);auto *saveClose=buttons->addButton(LText(LocalText::SaveAndClose),QDialogButtonBox::AcceptRole);auto *cancel=buttons->addButton(LText(LocalText::Cancel),QDialogButtonBox::RejectRole);layout->addWidget(buttons);
        QWidget::setTabOrder(search,commands);QWidget::setTabOrder(commands,allowObsHotkeyControl);QWidget::setTabOrder(allowObsHotkeyControl,editButton);QWidget::setTabOrder(editButton,removeButton);QWidget::setTabOrder(removeButton,saveClose);QWidget::setTabOrder(saveClose,cancel);LoadData();refresh();commands->editRequested=[this]{editSelected();};commands->removeRequested=[this]{removeSelected();};commands->closeRequested=[this]{close();};QObject::connect(search,&QLineEdit::textChanged,[this]{refresh(selectedIndex());});QObject::connect(commands,&QListWidget::currentItemChanged,[this](QListWidgetItem*,QListWidgetItem*){updateButtons();});QObject::connect(commands,&QListWidget::itemDoubleClicked,[this](QListWidgetItem*){editSelected();});QObject::connect(editButton,&QPushButton::clicked,[this]{editSelected();});QObject::connect(removeButton,&QPushButton::clicked,[this]{removeSelected();});QObject::connect(saveClose,&QPushButton::clicked,[this]{if(saveAll()){closing=true;accept();}});QObject::connect(cancel,&QPushButton::clicked,[this]{close();});resize(900,740);search->setFocus(Qt::OtherFocusReason);
    }
    void focusSearch(){if(isMinimized())showNormal();else if(!isVisible())show();if(QApplication::activeWindow()!=this){raise();activateWindow();}if(QApplication::focusWidget()!=search)search->setFocus(Qt::OtherFocusReason);}
};

static void ShowQtHotkeyEditor(){
    if(qtHotkeyEditor){static_cast<QtHotkeyEditorDialog*>(qtHotkeyEditor.data())->focusSearch();return;}auto *editor=new QtHotkeyEditorDialog(obsMainWindow);qtHotkeyEditor=editor;editor->show();editor->raise();editor->activateWindow();
}

static void OpenUserManual(){
    std::vector<wchar_t> modulePath(32768);DWORD length=GetModuleFileNameW(instance,modulePath.data(),static_cast<DWORD>(modulePath.size()));if(!length||length>=modulePath.size()){QMessageBox::critical(obsMainWindow,QStringLiteral("Accessible Studio"),LText(LocalText::ManualOpenFailure));return;}
    QDir root=QFileInfo(QString::fromWCharArray(modulePath.data(),static_cast<int>(length))).absoluteDir();if(!root.cdUp()||!root.cdUp()){QMessageBox::critical(obsMainWindow,QStringLiteral("Accessible Studio"),LText(LocalText::ManualOpenFailure));return;}QDir docs(root.filePath(QStringLiteral("docs")));
    QString locale=QString::fromUtf8(api.get_locale?api.get_locale():"en-US").replace(u'_',u'-'),lower=locale.toLower(),canonical=QStringLiteral("en-US");if(lower.startsWith(QStringLiteral("de")))canonical=QStringLiteral("de-DE");else if(lower.startsWith(QStringLiteral("es")))canonical=QStringLiteral("es-ES");else if(lower.startsWith(QStringLiteral("fr")))canonical=QStringLiteral("fr-FR");else if(lower.startsWith(QStringLiteral("ru")))canonical=QStringLiteral("ru-RU");else if(lower.startsWith(QStringLiteral("uk")))canonical=QStringLiteral("uk-UA");
    QStringList candidates{locale,canonical,QStringLiteral("en-US")};candidates.removeDuplicates();QString manual;for(const QString &candidate:candidates){QString path=docs.filePath(QStringLiteral("README.%1.html").arg(candidate));if(QFileInfo::exists(path)){manual=path;break;}}if(manual.isEmpty()||!QDesktopServices::openUrl(QUrl::fromLocalFile(manual)))QMessageBox::critical(obsMainWindow,QStringLiteral("Accessible Studio"),LText(LocalText::ManualOpenFailure));
}

static void ShowAccessibleToolsMenu(){
    if(!accessibleToolsMenu||!obsMainWindow)return;QPoint position=obsMainWindow->mapToGlobal(QPoint(12,obsMainWindow->menuBar()?obsMainWindow->menuBar()->height()+4:32));if(!accessibleToolsMenu->actions().isEmpty())accessibleToolsMenu->setActiveAction(accessibleToolsMenu->actions().front());accessibleToolsMenu->popup(position);
}

static bool InitializeAccessibleToolsAction(){
    if(!api.add_tools_qaction||!obsMainWindow)return false;auto *action=static_cast<QAction*>(api.add_tools_qaction("Accessible Studio"));if(!action)return false;accessibleToolsAction=action;auto *menu=new QMenu(obsMainWindow);accessibleToolsMenu=menu;action->setMenu(menu);
    QMenu *audio=menu->addMenu(LText(LocalText::AudioTools));QAction *volume=audio->addAction(LText(LocalText::AccessibleVolumeConsoleMenu));audibleMeterMenuAction=audio->addAction(LText(LocalText::AudibleMeterMenu));audibleMeterMenuAction->setCheckable(true);QAction *doctor=audio->addAction(LText(LocalText::SoundDoctorMenu));audio->addSeparator();QAction *advanced=audio->addAction(LText(LocalText::AdvancedSoundSettings));
    QMenu *video=menu->addMenu(LText(LocalText::VideoTools));QAction *shortDescription=video->addAction(LText(LocalText::ShortCanvasDescription));QAction *detailed=video->addAction(CText(CanvasText::DetailedDescription));QAction *readText=video->addAction(CText(CanvasText::ReadText));QAction *people=video->addAction(CText(CanvasText::PeopleBackgrounds));QAction *checker=video->addAction(CText(CanvasText::AnalyzeIssues));video->addSeparator();QAction *keys=video->addAction(LText(LocalText::ManageOpenAiApiKeys));
    menu->addSeparator();QAction *editor=menu->addAction(LText(LocalText::ShortcutEditor));QAction *manual=menu->addAction(LText(LocalText::OpenUserManual));
    QObject::connect(volume,&QAction::triggered,[]{OpenVolumeConsole();});QObject::connect(audibleMeterMenuAction,&QAction::triggered,[]{ToggleAudibleMeter();});QObject::connect(doctor,&QAction::triggered,[]{ActivateSoundDoctor();});QObject::connect(advanced,&QAction::triggered,[]{ShowAdvancedSoundSettings();});
    auto canvas=[](CanvasMode mode){StartCanvasCapture(mode,false,false,{});};QObject::connect(shortDescription,&QAction::triggered,[canvas]{canvas(CanvasMode::Basic);});QObject::connect(detailed,&QAction::triggered,[canvas]{canvas(CanvasMode::Detailed);});QObject::connect(readText,&QAction::triggered,[canvas]{canvas(CanvasMode::ReadText);});QObject::connect(people,&QAction::triggered,[canvas]{canvas(CanvasMode::PeopleBackgrounds);});QObject::connect(checker,&QAction::triggered,[canvas]{canvas(CanvasMode::AnalyzeIssues);});QObject::connect(keys,&QAction::triggered,[]{ShowSettings();});QObject::connect(editor,&QAction::triggered,[]{ShowQtHotkeyEditor();});QObject::connect(manual,&QAction::triggered,[]{OpenUserManual();});return true;
}
