// SPDX-License-Identifier: GPL-2.0-or-later
// Copyright (C) 2026 Tiflo.Info

namespace SoundDoctor {
constexpr uint32_t AUDIO_FLAG=1u<<1;
constexpr int MAX_CHANNELS=8,FADER_LOG=2,MIN_DB=-100,MAX_DB=20,BINS=121;
constexpr int MONITOR_SECONDS=120,REFRESH_MS=1000;
constexpr double DEFAULT_MIN_ACTIVE_SECONDS=45.0,DEFAULT_MIN_COMPRESSION_SPREAD_DB=8.0,DEFAULT_MAX_COMPRESSION_RATIO=3.0,DEFAULT_LIMITER_THRESHOLD_DB=-3.0;
constexpr bool DEFAULT_LIMITER_ALL_ACTIVE_SOURCES=false;
using Text=std::array<const char*,6>;
static QString T(const Text &text){
    size_t language=LanguageIndex();QString value=QString::fromUtf8(text[language]);
    if(language==2)value.replace(QStringLiteral("Запустить Sound Doctor"),QStringLiteral("Запустить Консультанта по звуку")).replace(QStringLiteral("Перед запуском Sound Doctor"),QStringLiteral("Перед запуском Консультанта по звуку")).replace(QStringLiteral("Рекомендации Sound Doctor"),QStringLiteral("Рекомендации Консультанта по звуку")).replace(QStringLiteral("Sound Doctor – Compressor"),QStringLiteral("Консультант по звуку – Компрессор")).replace(QStringLiteral("Sound Doctor – Limiter"),QStringLiteral("Консультант по звуку – Лимитер")).replace(QStringLiteral("Sound Doctor"),QStringLiteral("Консультант по звуку")).replace(QStringLiteral("Audible Meter"),QStringLiteral("Звуковой индикатор"));
    else if(language==3)value.replace(QStringLiteral("Запустити Sound Doctor"),QStringLiteral("Запустити Консультанта зі звуку")).replace(QStringLiteral("Перед запуском Sound Doctor"),QStringLiteral("Перед запуском Консультанта зі звуку")).replace(QStringLiteral("Рекомендації Sound Doctor"),QStringLiteral("Рекомендації Консультанта зі звуку")).replace(QStringLiteral("Sound Doctor – Compressor"),QStringLiteral("Консультант зі звуку – Компресор")).replace(QStringLiteral("Sound Doctor – Limiter"),QStringLiteral("Консультант зі звуку – Лімітер")).replace(QStringLiteral("Sound Doctor"),QStringLiteral("Консультант зі звуку")).replace(QStringLiteral("Audible Meter"),QStringLiteral("Звуковий індикатор"));
    return value;
}

static const Text COMMAND={".Run Sound Doctor",".Sound Doctor ausführen",".Запустить Sound Doctor",".Запустити Sound Doctor",".Exécuter Sound Doctor",".Ejecutar Sound Doctor"};
static const Text TITLE={"Sound Doctor","Sound Doctor","Sound Doctor","Sound Doctor","Sound Doctor","Sound Doctor"};
static const Text COMPRESSOR_NAME={"Sound Doctor – Compressor","Sound Doctor – Compressor","Консультант по звуку – Компрессор","Консультант зі звуку – Компресор","Sound Doctor – Compressor","Sound Doctor – Compressor"};
static const Text LIMITER_NAME={"Sound Doctor – Limiter","Sound Doctor – Limiter","Консультант по звуку – Лимитер","Консультант зі звуку – Лімітер","Sound Doctor – Limiter","Sound Doctor – Limiter"};
static const Text APPLY_UNDO={"Apply Sound Doctor recommendations","Apply Sound Doctor recommendations","Применить рекомендации Консультанта по звуку","Застосувати рекомендації Консультанта зі звуку","Apply Sound Doctor recommendations","Apply Sound Doctor recommendations"};
static const Text INTRO={"Sound Doctor monitors active audio sources for about two minutes, then presents recommendations. If streaming or recording is active, monitoring may continue and the recommendations will appear after both have stopped. No audio is recorded or saved. After choosing Start, use your audio sources normally.","Sound Doctor überwacht aktive Audioquellen etwa zwei Minuten lang und zeigt anschließend Empfehlungen an. Wenn Streaming oder eine Aufnahme aktiv ist, kann die Überwachung fortgesetzt werden; die Empfehlungen erscheinen, nachdem beides beendet wurde. Es wird kein Audio aufgenommen oder gespeichert. Verwenden Sie Ihre Audioquellen nach dem Start wie gewohnt.","Sound Doctor наблюдает за активными аудиоисточниками около двух минут, а затем показывает рекомендации. Если идёт трансляция или запись, наблюдение может продолжиться, а рекомендации появятся после остановки обоих процессов. Звук не записывается и не сохраняется. После запуска используйте аудиоисточники как обычно.","Sound Doctor спостерігає за активними аудіоджерелами близько двох хвилин, а потім показує рекомендації. Якщо триває трансляція або запис, спостереження може продовжитися, а рекомендації з’являться після зупинки обох процесів. Звук не записується й не зберігається. Після запуску використовуйте аудіоджерела як звичайно.","Sound Doctor surveille les sources audio actives pendant environ deux minutes, puis présente ses recommandations. Si une diffusion ou un enregistrement est actif, la surveillance peut continuer et les recommandations apparaîtront après l’arrêt des deux. Aucun son n’est enregistré ni sauvegardé. Après avoir choisi Démarrer, utilisez normalement vos sources audio.","Sound Doctor supervisa las fuentes de audio activas durante unos dos minutos y después presenta recomendaciones. Si hay una transmisión o grabación activa, la supervisión puede continuar y las recomendaciones aparecerán cuando ambas hayan terminado. No se graba ni se guarda audio. Después de elegir Iniciar, utilice sus fuentes de audio con normalidad."};
static const Text INTRO_LIVE={"A stream or recording is active. Sound Doctor will monitor for at least two minutes and show recommendations after both streaming and recording have stopped. No audio is recorded or saved. After choosing Start, continue normally.","Ein Stream oder eine Aufnahme ist aktiv. Sound Doctor überwacht mindestens zwei Minuten lang und zeigt die Empfehlungen an, nachdem Streaming und Aufnahme beendet wurden. Es wird kein Audio aufgenommen oder gespeichert. Fahren Sie nach dem Start wie gewohnt fort.","Сейчас идёт трансляция или запись. Sound Doctor будет наблюдать не менее двух минут и покажет рекомендации после остановки и трансляции, и записи. Звук не записывается и не сохраняется. После запуска продолжайте работать как обычно.","Зараз триває трансляція або запис. Sound Doctor спостерігатиме щонайменше дві хвилини й покаже рекомендації після зупинки і трансляції, і запису. Звук не записується й не зберігається. Після запуску продовжуйте працювати як звичайно.","Une diffusion ou un enregistrement est actif. Sound Doctor surveillera pendant au moins deux minutes et affichera ses recommandations après l’arrêt de la diffusion et de l’enregistrement. Aucun son n’est enregistré ni sauvegardé. Après avoir choisi Démarrer, poursuivez normalement.","Hay una transmisión o grabación activa. Sound Doctor supervisará durante al menos dos minutos y mostrará las recomendaciones cuando se hayan detenido tanto la transmisión como la grabación. No se graba ni se guarda audio. Después de elegir Iniciar, continúe con normalidad."};
static const Text START={"Start","Starten","Начать","Почати","Démarrer","Iniciar"};
static const Text NOT_NOW={"Not Now","Nicht jetzt","Не сейчас","Не зараз","Pas maintenant","Ahora no"};
static const Text RUNNING={"Sound Doctor started. Monitoring for about two minutes.","Sound Doctor wurde gestartet. Die Überwachung dauert etwa zwei Minuten.","Sound Doctor запущен. Наблюдение продлится около двух минут.","Sound Doctor запущено. Спостереження триватиме близько двох хвилин.","Sound Doctor a démarré. La surveillance durera environ deux minutes.","Sound Doctor se ha iniciado. La supervisión durará unos dos minutos."};
static const Text ALREADY_RUNNING={"Sound Doctor is already monitoring. About %1 seconds remain.","Sound Doctor überwacht bereits. Noch etwa %1 Sekunden.","Sound Doctor уже выполняет наблюдение. Осталось около %1 секунд.","Sound Doctor уже виконує спостереження. Залишилося близько %1 секунд.","Sound Doctor effectue déjà la surveillance. Il reste environ %1 secondes.","Sound Doctor ya está supervisando. Quedan unos %1 segundos."};
static const Text WAITING_FOR_OUTPUTS={"Sound Doctor has gathered at least two minutes of information and will continue monitoring. Its report will appear after streaming and recording have stopped.","Sound Doctor hat mindestens zwei Minuten lang Daten gesammelt und überwacht weiter. Der Bericht wird angezeigt, nachdem Streaming und Aufnahme beendet wurden.","Sound Doctor собрал данные как минимум за две минуты и продолжит наблюдение. Отчёт появится после остановки трансляции и записи.","Sound Doctor зібрав дані щонайменше за дві хвилини й продовжить спостереження. Звіт з’явиться після зупинки трансляції та запису.","Sound Doctor a recueilli au moins deux minutes de données et poursuit la surveillance. Le rapport apparaîtra après l’arrêt de la diffusion et de l’enregistrement.","Sound Doctor ha recopilado al menos dos minutos de información y seguirá supervisando. El informe aparecerá después de detener la transmisión y la grabación."};
static const Text AUDIBLE_ACTIVE={"Turn off Audible Meter before starting Sound Doctor.","Beenden Sie Audible Meter, bevor Sie Sound Doctor starten.","Перед запуском Sound Doctor выключите Audible Meter.","Перед запуском Sound Doctor вимкніть Audible Meter.","Désactivez Audible Meter avant de démarrer Sound Doctor.","Desactive Audible Meter antes de iniciar Sound Doctor."};
static const Text METER_BLOCKED={"Sound Doctor is monitoring. Audible Meter was not started.","Sound Doctor überwacht gerade. Audible Meter wurde nicht gestartet.","Sound Doctor выполняет наблюдение. Audible Meter не был запущен.","Sound Doctor виконує спостереження. Audible Meter не запущено.","Sound Doctor effectue une surveillance. Audible Meter n’a pas démarré.","Sound Doctor está supervisando. Audible Meter no se ha iniciado."};
static const Text CANCELLED={"Sound Doctor stopped because the profile or scene collection changed.","Sound Doctor wurde beendet, weil das Profil oder die Szenensammlung geändert wurde.","Sound Doctor остановлен из-за изменения профиля или коллекции сцен.","Sound Doctor зупинено через зміну профілю або колекції сцен.","Sound Doctor s’est arrêté, car le profil ou la collection de scènes a changé.","Sound Doctor se detuvo porque cambió el perfil o la colección de escenas."};
static const Text INTERRUPT_QUESTION={"Sound Doctor is currently working. Do you want to interrupt this process and discard the results?","Sound Doctor arbeitet derzeit. Möchten Sie den Vorgang unterbrechen und die Ergebnisse verwerfen?","Sound Doctor сейчас работает. Прервать процесс и удалить результаты?","Sound Doctor зараз працює. Перервати процес і відкинути результати?","Sound Doctor travaille actuellement. Voulez-vous interrompre ce processus et supprimer les résultats ?","Sound Doctor está trabajando. ¿Desea interrumpir el proceso y descartar los resultados?"};
static const Text DONT_SHOW_INTERRUPT={"Don’t show this message again","Diese Meldung nicht mehr anzeigen","Больше не показывать это сообщение","Більше не показувати це повідомлення","Ne plus afficher ce message","No volver a mostrar este mensaje"};
static const Text INTERRUPTED={"Sound Doctor interrupted. Collected measurements were discarded.","Sound Doctor wurde unterbrochen. Die erfassten Messwerte wurden verworfen.","Sound Doctor прерван. Собранные измерения удалены.","Sound Doctor перервано. Зібрані вимірювання відкинуто.","Sound Doctor a été interrompu. Les mesures recueillies ont été supprimées.","Sound Doctor se ha interrumpido. Se descartaron las mediciones recopiladas."};
static const Text INTERRUPT_SAVE_FAILED={"Sound Doctor was interrupted, but the warning preference could not be saved.","Sound Doctor wurde unterbrochen, aber die Warneinstellung konnte nicht gespeichert werden.","Sound Doctor прерван, но не удалось сохранить настройку предупреждения.","Sound Doctor перервано, але не вдалося зберегти налаштування попередження.","Sound Doctor a été interrompu, mais la préférence d’avertissement n’a pas pu être enregistrée.","Sound Doctor se interrumpió, pero no se pudo guardar la preferencia del aviso."};
static const Text RESULTS_HEADING={"Sound Doctor recommendations","Sound Doctor-Empfehlungen","Рекомендации Sound Doctor","Рекомендації Sound Doctor","Recommandations de Sound Doctor","Recomendaciones de Sound Doctor"};
static const Text RESULTS_INTRO={"Review the evidence and select only the changes you want Sound Doctor to apply. These are conservative starting points; listen to the result and adjust if necessary.","Prüfen Sie die Daten und wählen Sie nur die Änderungen aus, die Sound Doctor anwenden soll. Dies sind vorsichtige Ausgangswerte; hören Sie sich das Ergebnis an und passen Sie es bei Bedarf an.","Изучите данные и выберите только те изменения, которые Sound Doctor должен применить. Это осторожные начальные значения; прослушайте результат и при необходимости настройте их.","Перегляньте дані й виберіть лише ті зміни, які Sound Doctor має застосувати. Це обережні початкові значення; прослухайте результат і за потреби відкоригуйте їх.","Examinez les données et sélectionnez uniquement les modifications que Sound Doctor doit appliquer. Il s’agit de points de départ prudents ; écoutez le résultat et ajustez-le si nécessaire.","Revise los datos y seleccione solo los cambios que desea que aplique Sound Doctor. Son puntos de partida prudentes; escuche el resultado y ajústelos si es necesario."};
static const Text APPLY_CHANGE={"Apply this change automatically","Diese Änderung automatisch anwenden","Применить это изменение автоматически","Застосувати цю зміну автоматично","Appliquer automatiquement cette modification","Aplicar este cambio automáticamente"};
static const Text APPLY_FOR={"Apply this change automatically for %1","Diese Änderung für %1 automatisch anwenden","Автоматически применить это изменение к %1","Автоматично застосувати цю зміну до %1","Appliquer automatiquement cette modification à %1","Aplicar automáticamente este cambio a %1"};
static const Text FINISH={"Finish","Fertigstellen","Готово","Завершити","Terminer","Finalizar"};
static const Text FINISH_ACCESSIBLE={"Finish and apply the selected changes","Fertigstellen und ausgewählte Änderungen anwenden","Завершить и применить выбранные изменения","Завершити й застосувати вибрані зміни","Terminer et appliquer les modifications sélectionnées","Finalizar y aplicar los cambios seleccionados"};
static const Text NO_CHANGES={"Sound Doctor did not find any changes it could recommend confidently. Sources with too little active audio or existing protection were left unchanged.","Sound Doctor hat keine Änderungen gefunden, die mit ausreichender Sicherheit empfohlen werden konnten. Quellen mit zu wenig aktivem Audio oder vorhandenem Schutz wurden nicht geändert.","Sound Doctor не нашёл изменений, которые можно уверенно рекомендовать. Источники с недостаточным активным звуком или уже существующей защитой оставлены без изменений.","Sound Doctor не знайшов змін, які можна впевнено рекомендувати. Джерела з недостатньою активністю або наявним захистом залишено без змін.","Sound Doctor n’a trouvé aucune modification qu’il pouvait recommander avec suffisamment de certitude. Les sources avec trop peu d’audio actif ou une protection existante n’ont pas été modifiées.","Sound Doctor no encontró cambios que pudiera recomendar con suficiente confianza. Las fuentes con muy poco audio activo o con protección existente no se modificaron."};
static const Text INSUFFICIENT={"%1 was active for only %2 seconds, so no processing change is recommended.","%1 war nur %2 Sekunden aktiv; daher wird keine Änderung der Verarbeitung empfohlen.","Источник %1 был активен только %2 секунд, поэтому изменение обработки не рекомендуется.","Джерело %1 було активним лише %2 секунд, тому змінювати обробку не рекомендовано.","%1 n’a été actif que pendant %2 secondes ; aucune modification du traitement n’est donc recommandée.","%1 estuvo activo solo durante %2 segundos, por lo que no se recomienda cambiar el procesamiento."};
static const Text EXISTING_COMPRESSOR={"A compressor already exists. Sound Doctor will not add another one.","Ein Kompressor ist bereits vorhanden. Sound Doctor fügt keinen weiteren hinzu.","Компрессор уже существует. Sound Doctor не будет добавлять ещё один.","Компресор уже існує. Sound Doctor не додаватиме ще один.","Un compresseur existe déjà. Sound Doctor n’en ajoutera pas un autre.","Ya existe un compresor. Sound Doctor no añadirá otro."};
static const Text EXISTING_LIMITER={"A limiter already exists. Sound Doctor will not add another one.","Ein Limiter ist bereits vorhanden. Sound Doctor fügt keinen weiteren hinzu.","Лимитер уже существует. Sound Doctor не будет добавлять ещё один.","Лімітер уже існує. Sound Doctor не додаватиме ще один.","Un limiteur existe déjà. Sound Doctor n’en ajoutera pas un autre.","Ya existe un limitador. Sound Doctor no añadirá otro."};
static const Text CHANGED_DURING_TEST={"The source level or filter chain changed during the test, so Sound Doctor did not calculate a processing change.","Der Quellenpegel oder die Filterkette wurde während des Tests geändert; daher hat Sound Doctor keine Verarbeitungsänderung berechnet.","Во время теста изменился уровень источника или цепочка фильтров, поэтому Sound Doctor не рассчитывал изменение обработки.","Під час тесту змінився рівень джерела або ланцюжок фільтрів, тому Sound Doctor не розраховував зміну обробки.","Le niveau de la source ou la chaîne de filtres a changé pendant le test ; Sound Doctor n’a donc pas calculé de modification du traitement.","El nivel de la fuente o la cadena de filtros cambió durante la prueba, por lo que Sound Doctor no calculó ningún cambio de procesamiento."};
static const Text COMPRESSOR_REASON={"Typical and loud passages differed by about %1 dB. A compressor can make this likely live input more consistent. If the source is primarily music, leave this recommendation unselected.","Typische und laute Passagen unterschieden sich um etwa %1 dB. Ein Kompressor kann diesen wahrscheinlichen Live-Eingang gleichmäßiger machen. Wenn die Quelle hauptsächlich Musik enthält, lassen Sie diese Empfehlung deaktiviert.","Типичные и громкие фрагменты отличались примерно на %1 дБ. Компрессор может сделать этот вероятный живой вход более ровным. Если источник содержит преимущественно музыку, не выбирайте эту рекомендацию.","Типові й гучні фрагменти відрізнялися приблизно на %1 дБ. Компресор може зробити цей імовірний живий вхід рівномірнішим. Якщо джерело містить переважно музику, не вибирайте цю рекомендацію.","Les passages typiques et forts différaient d’environ %1 dB. Un compresseur peut rendre cette entrée probablement en direct plus régulière. Si la source contient principalement de la musique, ne sélectionnez pas cette recommandation.","Los pasajes habituales y fuertes diferían aproximadamente %1 dB. Un compresor puede hacer más uniforme esta probable entrada en directo. Si la fuente contiene principalmente música, no seleccione esta recomendación."};
static const Text LIMITER_REASON={"No limiter was found on this active source. Adding one last in the filter chain provides protection against unexpected peaks while leaving audio below its ceiling unchanged.","Für diese aktive Quelle wurde kein Limiter gefunden. Ein Limiter am Ende der Filterkette schützt vor unerwarteten Spitzen und lässt Audio unterhalb seines Grenzwerts unverändert.","У этого активного источника не найден лимитер. Лимитер в конце цепочки фильтров защищает от неожиданных пиков и не изменяет звук ниже установленного предела.","Для цього активного джерела не знайдено лімітера. Лімітер наприкінці ланцюжка фільтрів захищає від неочікуваних піків і не змінює звук нижче встановленої межі.","Aucun limiteur n’a été trouvé sur cette source active. L’ajouter en dernier dans la chaîne protège contre les crêtes inattendues sans modifier l’audio sous son plafond.","No se encontró ningún limitador en esta fuente activa. Añadirlo al final de la cadena protege frente a picos inesperados sin modificar el audio que esté por debajo de su límite."};
static const Text COMPRESSOR_SETTINGS={"Add “Sound Doctor – Compressor” after the existing filters: threshold %1 dB, ratio %2:1, attack 6 ms, release 100 ms, output gain 0 dB.","„Sound Doctor – Compressor“ nach den vorhandenen Filtern hinzufügen: Schwellenwert %1 dB, Verhältnis %2:1, Attack 6 ms, Release 100 ms, Ausgangsverstärkung 0 dB.","Добавить «Sound Doctor – Compressor» после существующих фильтров: порог %1 дБ, соотношение %2:1, атака 6 мс, восстановление 100 мс, выходное усиление 0 дБ.","Додати «Sound Doctor – Compressor» після наявних фільтрів: поріг %1 дБ, співвідношення %2:1, атака 6 мс, відновлення 100 мс, вихідне підсилення 0 дБ.","Ajouter « Sound Doctor – Compressor » après les filtres existants : seuil %1 dB, rapport %2:1, attaque 6 ms, relâchement 100 ms, gain de sortie 0 dB.","Añadir «Sound Doctor – Compressor» después de los filtros existentes: umbral %1 dB, relación %2:1, ataque 6 ms, liberación 100 ms, ganancia de salida 0 dB."};
static const Text LIMITER_SETTINGS={"Add “Sound Doctor – Limiter” last in the filter chain: threshold %1 dB and release 60 ms.","„Sound Doctor – Limiter“ als letzten Filter hinzufügen: Schwellenwert %1 dB und Release 60 ms.","Добавить «Sound Doctor – Limiter» последним в цепочке: порог %1 дБ и восстановление 60 мс.","Додати «Sound Doctor – Limiter» останнім у ланцюжку: поріг %1 дБ і відновлення 60 мс.","Ajouter « Sound Doctor – Limiter » en dernier dans la chaîne : seuil %1 dB et relâchement 60 ms.","Añadir «Sound Doctor – Limiter» al final de la cadena: umbral %1 dB y liberación 60 ms."};
static const Text APPLY_SUMMARY={"Sound Doctor applied %1 change(s).","Sound Doctor hat %1 Änderung(en) angewendet.","Sound Doctor применил изменений: %1.","Sound Doctor застосував змін: %1.","Sound Doctor a appliqué %1 modification(s).","Sound Doctor aplicó %1 cambio(s)."};
static const Text APPLY_PARTIAL={"%1 selected change(s) could not be applied because the source or filter chain had changed.","%1 ausgewählte Änderung(en) konnten nicht angewendet werden, weil sich die Quelle oder Filterkette geändert hatte.","Не удалось применить выбранные изменения (%1), поскольку источник или цепочка фильтров изменились.","Не вдалося застосувати вибрані зміни (%1), оскільки джерело або ланцюжок фільтрів змінилися.","%1 modification(s) sélectionnée(s) n’ont pas pu être appliquées, car la source ou la chaîne avait changé.","No se pudieron aplicar %1 cambios seleccionados porque la fuente o la cadena de filtros habían cambiado."};
static const Text OBSERVATIONS={"Observations","Beobachtungen","Наблюдения","Спостереження","Observations","Observaciones"};
static const Text PREFADER_CLIPPING={"%1 produced %2 prefader peaks near clipping. Reduce the input or device gain; a filter cannot repair clipped audio.","%1 erzeugte %2 Spitzen vor dem Regler nahe der Übersteuerung. Reduzieren Sie den Eingangs- oder Gerätepegel; ein Filter kann bereits verzerrtes Audio nicht reparieren.","Источник %1 создал %2 пиков до регулятора вблизи клиппинга. Уменьшите входное усиление или усиление устройства; фильтр не может восстановить уже искажённый звук.","Джерело %1 створило %2 піків до регулятора поблизу кліпінгу. Зменште вхідне підсилення або підсилення пристрою; фільтр не може відновити вже спотворений звук.","%1 a produit %2 crêtes avant curseur proches de l’écrêtage. Réduisez le gain d’entrée ou de l’appareil ; un filtre ne peut pas réparer un son déjà écrêté.","%1 produjo %2 picos antes del control cerca del recorte. Reduzca la ganancia de entrada o del dispositivo; un filtro no puede reparar audio ya recortado."};
static const Text WEBVIEW_FAILURE={"Sound Doctor could not initialize WebView2.","Sound Doctor konnte WebView2 nicht initialisieren.","Sound Doctor не удалось инициализировать WebView2.","Sound Doctor не вдалося ініціалізувати WebView2.","Sound Doctor n’a pas pu initialiser WebView2.","Sound Doctor no pudo inicializar WebView2."};
static const Text WINDOW_FAILURE={"Sound Doctor could not create the recommendations window.","Sound Doctor konnte das Empfehlungsfenster nicht erstellen.","Sound Doctor не удалось создать окно рекомендаций.","Sound Doctor не вдалося створити вікно рекомендацій.","Sound Doctor n’a pas pu créer la fenêtre des recommandations.","Sound Doctor no pudo crear la ventana de recomendaciones."};
static const Text ENABLED={"enabled","aktiviert","включён","увімкнено","activé","activado"};
static const Text DISABLED={"disabled","deaktiviert","отключён","вимкнено","désactivé","desactivado"};
static const Text COMPRESSOR_DETAILS={"Compressor “%1” is %2: threshold %3 dB, ratio %4:1, attack %5 ms, release %6 ms, output gain %7 dB.","Kompressor „%1“ ist %2: Schwellenwert %3 dB, Verhältnis %4:1, Attack %5 ms, Release %6 ms, Ausgangsverstärkung %7 dB.","Компрессор «%1» %2: порог %3 дБ, соотношение %4:1, атака %5 мс, восстановление %6 мс, выходное усиление %7 дБ.","Компресор «%1» %2: поріг %3 дБ, співвідношення %4:1, атака %5 мс, відновлення %6 мс, вихідне підсилення %7 дБ.","Le compresseur « %1 » est %2 : seuil %3 dB, rapport %4:1, attaque %5 ms, relâchement %6 ms, gain de sortie %7 dB.","El compresor «%1» está %2: umbral %3 dB, relación %4:1, ataque %5 ms, liberación %6 ms, ganancia de salida %7 dB."};
static const Text LIMITER_DETAILS={"Limiter “%1” is %2: threshold %3 dB and release %4 ms.","Limiter „%1“ ist %2: Schwellenwert %3 dB und Release %4 ms.","Лимитер «%1» %2: порог %3 дБ и восстановление %4 мс.","Лімітер «%1» %2: поріг %3 дБ і відновлення %4 мс.","Le limiteur « %1 » est %2 : seuil %3 dB et relâchement %4 ms.","El limitador «%1» está %2: umbral %3 dB y liberación %4 ms."};
static const Text LIMITER_NOT_LAST={"This limiter is not last in the filter chain. For reliable peak protection, move it after the other filters.","Dieser Limiter steht nicht am Ende der Filterkette. Verschieben Sie ihn für zuverlässigen Spitzenschutz hinter die anderen Filter.","Этот лимитер не является последним в цепочке. Для надёжной защиты от пиков переместите его после остальных фильтров.","Цей лімітер не є останнім у ланцюжку. Для надійного захисту від піків перемістіть його після інших фільтрів.","Ce limiteur n’est pas le dernier de la chaîne. Pour une protection fiable contre les crêtes, placez-le après les autres filtres.","Este limitador no es el último de la cadena. Para una protección fiable contra picos, muévalo después de los demás filtros."};

enum class Kind{Compressor,Limiter};
struct FilterInfo{QString name,type,settingsFingerprint;bool enabled{},managed{};double threshold{},ratio{},outputGain{};long long attack{},release{};};
struct Source {
    void *source{};obs_volmeter *meter{};QString uuid,name,type,initialFilterFingerprint;int channels{2};float initialVolume{1.0f};
    std::mutex mutex;std::chrono::steady_clock::time_point lastCallback{};
    std::array<uint64_t,BINS> rmsBins{},peakBins{};double activeMs{},maxPeak{-INFINITY};uint64_t peakEvents{},inputClipEvents{};
    bool highPeak{},inputClipping{},levelChanged{};
};
struct Recommendation{QString id,uuid,sourceName,expectedFilterFingerprint;Kind kind{};double threshold{},ratio{};float expectedVolume{1.0f};QString reason,settings;};
static std::vector<std::unique_ptr<Source>> sources;
static std::vector<Recommendation> recommendations;
static QStringList observations;
static QPointer<QTimer> timer;
static QElapsedTimer elapsed;
static std::atomic_bool running{};
static bool promptOpen{};
static bool waitingAnnouncementMade{};
static bool resultsDeferred{};
static HWND resultsWindow{};
static uint64_t resultsGeneration{};
static bool applyingResults{};
static Microsoft::WRL::ComPtr<ICoreWebView2Controller> controller;
static Microsoft::WRL::ComPtr<ICoreWebView2> webView;
static EventRegistrationToken messageToken{},navigationToken{},acceleratorToken{};
static std::atomic_int pendingWebViewInitializations{};
static QPointer<QWidget> returnFocus;

static bool OutputsActive(){return (api.streaming_active&&api.streaming_active())||(api.recording_active&&api.recording_active());}
static double Setting(const char *name,double fallback,double minimum,double maximum){return ConfiguredDouble(api.global_config?api.global_config():nullptr,name,fallback,minimum,maximum);}
static double MinimumCompressionSpreadDb(){return Setting("SoundDoctorMinimumCompressionSpreadDb",DEFAULT_MIN_COMPRESSION_SPREAD_DB,6.0,15.0);}
static double MaximumCompressionRatio(){return Setting("SoundDoctorMaximumCompressionRatio",DEFAULT_MAX_COMPRESSION_RATIO,2.5,3.5);}
static bool LimiterAllActiveSources(){config *cfg=api.global_config?api.global_config():nullptr;return cfg&&api.config_has_user_value(cfg,"AccessibleStudio","SoundDoctorLimiterAllActiveSources")?api.config_get_double(cfg,"AccessibleStudio","SoundDoctorLimiterAllActiveSources")>=0.5:DEFAULT_LIMITER_ALL_ACTIVE_SOURCES;}
static double LimiterThresholdDb(){return Setting("SoundDoctorLimiterThresholdDb",DEFAULT_LIMITER_THRESHOLD_DB,-12.0,-1.0);}

static int Bin(double db){return std::clamp(static_cast<int>(std::lround(db))-MIN_DB,0,BINS-1);}
static double Percentile(const std::array<uint64_t,BINS> &bins,double fraction){
    uint64_t total=0;for(uint64_t count:bins)total+=count;if(!total)return -INFINITY;
    uint64_t target=std::max<uint64_t>(1,static_cast<uint64_t>(std::ceil(total*fraction))),sum=0;
    for(int i=0;i<BINS;++i){sum+=bins[static_cast<size_t>(i)];if(sum>=target)return i+MIN_DB;}return MAX_DB;
}
static bool MicrophoneType(const QString &type){return type==QStringLiteral("wasapi_input_capture")||type==QStringLiteral("dshow_input");}

static void EnumFilter(void*,void *filter,void *parameter){
    auto *items=static_cast<std::vector<FilterInfo>*>(parameter);QString type=QString::fromUtf8(api.source_id(filter)?api.source_id(filter):""),name=QString::fromUtf8(api.source_name(filter)?api.source_name(filter):"");
    obs_data *settings=api.source_settings(filter);bool managed=settings&&api.data_get_bool(settings,"sound_doctor_managed");QByteArray json;double threshold=0,ratio=0,outputGain=0;long long attack=0,release=0;if(settings){const char *raw=api.data_json(settings);if(raw)json=raw;threshold=api.data_get_double(settings,"threshold");ratio=api.data_get_double(settings,"ratio");outputGain=api.data_get_double(settings,"output_gain");attack=api.data_get_int(settings,"attack_time");release=api.data_get_int(settings,"release_time");api.data_release(settings);}
    QString fingerprint=QString::fromLatin1(QCryptographicHash::hash(json,QCryptographicHash::Sha256).toHex());items->push_back({name,type,fingerprint,api.source_enabled(filter),managed,threshold,ratio,outputGain,attack,release});
}
static std::vector<FilterInfo> Filters(void *source){std::vector<FilterInfo> result;if(source)api.enum_filters(source,EnumFilter,&result);return result;}
static QString FilterFingerprint(void *source){
    QJsonArray values;for(const FilterInfo &filter:Filters(source))values.append(QJsonObject{{"name",filter.name},{"type",filter.type},{"settings",filter.settingsFingerprint},{"enabled",filter.enabled},{"managed",filter.managed}});
    return QString::fromLatin1(QCryptographicHash::hash(QJsonDocument(values).toJson(QJsonDocument::Compact),QCryptographicHash::Sha256).toHex());
}
static void Meter(void *parameter,const float *magnitude,const float *peak,const float *inputPeak){
    auto *source=static_cast<Source*>(parameter);if(!source||!running.load()||!magnitude||!peak||!inputPeak)return;
    double rms=-INFINITY,peakDb=-INFINITY,input=-INFINITY;for(int i=0;i<std::clamp(source->channels,1,MAX_CHANNELS);++i){if(std::isfinite(magnitude[i]))rms=std::max(rms,double(magnitude[i]));if(std::isfinite(peak[i]))peakDb=std::max(peakDb,double(peak[i]));if(std::isfinite(inputPeak[i]))input=std::max(input,double(inputPeak[i]));}
    auto now=std::chrono::steady_clock::now();std::unique_lock<std::mutex> lock(source->mutex,std::try_to_lock);if(!lock.owns_lock()||!running.load())return;
    double delta=source->lastCallback.time_since_epoch().count()?std::chrono::duration<double,std::milli>(now-source->lastCallback).count():0;source->lastCallback=now;delta=std::clamp(delta,0.0,100.0);
    float volume=source->source?api.source_get_volume(source->source):source->initialVolume;if(std::abs(volume-source->initialVolume)>std::max(0.001f,std::abs(source->initialVolume)*0.01f))source->levelChanged=true;
    rms=Reliability::PreFaderDb(rms,volume);
    if(std::isfinite(rms)&&rms>=-60.0){source->activeMs+=delta;++source->rmsBins[static_cast<size_t>(Bin(rms))];if(std::isfinite(peakDb)){++source->peakBins[static_cast<size_t>(Bin(peakDb))];source->maxPeak=std::max(source->maxPeak,peakDb);if(peakDb>=-3.0&&!source->highPeak){++source->peakEvents;source->highPeak=true;}}}if(!std::isfinite(peakDb)||peakDb<-6.0)source->highPeak=false;
    if(std::isfinite(input)){if(input>=-1.0&&!source->inputClipping){++source->inputClipEvents;source->inputClipping=true;}else if(input<-4.0)source->inputClipping=false;}
}
static void Detach(Source &source){if(source.meter){api.volmeter_remove_callback(source.meter,Meter,&source);api.volmeter_detach(source.meter);api.volmeter_destroy(source.meter);source.meter=nullptr;}if(source.source){api.source_release(source.source);source.source=nullptr;}}
static bool Attach(Source &source,void *enumerated){
    void *reference=api.source_get_ref(enumerated);if(!reference)return false;obs_volmeter *meter=api.volmeter_create(FADER_LOG);if(!meter){api.source_release(reference);return false;}api.volmeter_set_peak_type(meter,CurrentPeakType());
    if(!api.volmeter_attach(meter,reference)){api.volmeter_remove_callback(meter,Meter,&source);api.volmeter_destroy(meter);api.source_release(reference);return false;}
    float volume=api.source_get_volume(reference);QString fingerprint=FilterFingerprint(reference);if(source.initialFilterFingerprint.isEmpty()){source.initialVolume=volume;source.initialFilterFingerprint=fingerprint;}else if(std::abs(volume-source.initialVolume)>std::max(0.001f,std::abs(source.initialVolume)*0.01f)||fingerprint!=source.initialFilterFingerprint)source.levelChanged=true;
    source.source=reference;source.meter=meter;source.channels=std::clamp(api.volmeter_channels(meter),1,MAX_CHANNELS);source.lastCallback={};api.volmeter_add_callback(meter,Meter,&source);return true;
}
static bool Collect(void *parameter,void *enumerated){
    auto *active=static_cast<std::vector<QString>*>(parameter);if(!enumerated||(api.source_output_flags(enumerated)&AUDIO_FLAG)==0||!api.source_active(enumerated)||!api.source_audio_active(enumerated))return true;
    QString uuid=QString::fromUtf8(api.source_uuid(enumerated)?api.source_uuid(enumerated):"");if(uuid.isEmpty())return true;active->push_back(uuid);
    auto found=std::find_if(sources.begin(),sources.end(),[&](const auto &source){return source->uuid==uuid;});if(found==sources.end()){auto source=std::make_unique<Source>();source->uuid=uuid;source->name=QString::fromUtf8(api.source_name(enumerated)?api.source_name(enumerated):"Audio source");source->type=QString::fromUtf8(api.source_id(enumerated)?api.source_id(enumerated):"");if(Attach(*source,enumerated))sources.push_back(std::move(source));}else if(!(*found)->meter)Attach(*(*found),enumerated);
    return true;
}
static void Refresh(){
    if(!running.load())return;std::vector<QString> active;api.enum_sources(Collect,&active);
    for(auto &source:sources)if(source->meter&&std::find(active.begin(),active.end(),source->uuid)==active.end())Detach(*source);
}
struct Lookup{QString uuid;void *source{};};
static bool Find(void *parameter,void *enumerated){auto *lookup=static_cast<Lookup*>(parameter);QString uuid=QString::fromUtf8(api.source_uuid(enumerated)?api.source_uuid(enumerated):"");if(uuid!=lookup->uuid)return true;lookup->source=api.source_get_ref(enumerated);return false;}

static void Analyze(){
    recommendations.clear();observations.clear();int nextId=1;constexpr double minimumActiveMs=DEFAULT_MIN_ACTIVE_SECONDS*1000.0;double minimumSpread=MinimumCompressionSpreadDb(),maximumRatio=MaximumCompressionRatio(),limiterThreshold=LimiterThresholdDb();bool limiterAllSources=LimiterAllActiveSources();
    for(auto &source:sources){
        std::lock_guard<std::mutex> lock(source->mutex);Lookup lookup{source->uuid};api.enum_sources(Find,&lookup);void *current=lookup.source;QString currentFingerprint=current?FilterFingerprint(current):QString{};QStringList notes;
        std::vector<FilterInfo> filters=current?Filters(current):std::vector<FilterInfo>{};bool compressor=false,limiter=false;
        for(size_t index=0;index<filters.size();++index){const FilterInfo &filter=filters[index];QString state=T(filter.enabled?ENABLED:DISABLED);if(filter.type==QStringLiteral("compressor_filter")){compressor=true;notes.push_back(T(COMPRESSOR_DETAILS).arg(filter.name,state).arg(filter.threshold,0,'f',1).arg(filter.ratio,0,'f',1).arg(filter.attack).arg(filter.release).arg(filter.outputGain,0,'f',1));}if(filter.type==QStringLiteral("limiter_filter")){limiter=true;notes.push_back(T(LIMITER_DETAILS).arg(filter.name,state).arg(filter.threshold,0,'f',1).arg(filter.release));if(index+1<filters.size())notes.push_back(T(LIMITER_NOT_LAST));}}
        if(source->activeMs<minimumActiveMs)notes.push_back(T(INSUFFICIENT).arg(source->name).arg(std::lround(source->activeMs/1000.0)));if(compressor)notes.push_back(T(EXISTING_COMPRESSOR));if(limiter)notes.push_back(T(EXISTING_LIMITER));
        bool changed=source->levelChanged||!current||currentFingerprint!=source->initialFilterFingerprint;if(changed)notes.push_back(T(CHANGED_DURING_TEST));
        if(source->inputClipEvents>=3)notes.push_back(T(PREFADER_CLIPPING).arg(source->name).arg(source->inputClipEvents));
        if(!notes.isEmpty())observations.push_back(QStringLiteral("%1: %2").arg(source->name,notes.join(QLatin1Char(' '))));
        if(source->activeMs>=minimumActiveMs&&!changed){
            double median=Percentile(source->rmsBins,0.50),loud=Percentile(source->rmsBins,0.95),spread=loud-median;
            if(MicrophoneType(source->type)&&!compressor&&!limiter&&spread>=minimumSpread){
                double threshold=std::clamp(std::round(std::max(-24.0,median+5.0)),-24.0,-10.0),ratio=spread>=14.0?maximumRatio:spread>=10.0?std::min(2.5,maximumRatio):2.0;
                Recommendation item;item.id=QString::number(nextId++);item.uuid=source->uuid;item.sourceName=source->name;item.expectedFilterFingerprint=currentFingerprint;item.kind=Kind::Compressor;item.threshold=threshold;item.ratio=ratio;item.expectedVolume=current?api.source_get_volume(current):source->initialVolume;item.reason=T(COMPRESSOR_REASON).arg(spread,0,'f',0);item.settings=T(COMPRESSOR_SETTINGS).arg(threshold,0,'f',0).arg(ratio,0,'f',1);recommendations.push_back(std::move(item));
            }
            if((limiterAllSources||MicrophoneType(source->type))&&!limiter){
                Recommendation item;item.id=QString::number(nextId++);item.uuid=source->uuid;item.sourceName=source->name;item.expectedFilterFingerprint=currentFingerprint;item.kind=Kind::Limiter;item.threshold=limiterThreshold;item.expectedVolume=current?api.source_get_volume(current):source->initialVolume;item.reason=T(LIMITER_REASON);item.settings=T(LIMITER_SETTINGS).arg(limiterThreshold,0,'f',1);recommendations.push_back(std::move(item));
            }
        }
        if(current)api.source_release(current);
    }
}

static QString UniqueFilterName(void *source,const QString &base){
    for(int suffix=1;suffix<100;++suffix){QString candidate=suffix==1?base:QStringLiteral("%1 %2").arg(base).arg(suffix);QByteArray name=candidate.toUtf8();void *existing=api.source_filter_by_name(source,name.constData());if(!existing)return candidate;api.source_release(existing);}return {};
}
static bool HasFilter(void *source,const QString &type){for(const FilterInfo &filter:Filters(source))if(filter.type==type)return true;return false;}
static bool AddFilter(const Recommendation &item,QString *createdName=nullptr){
    Lookup lookup{item.uuid};api.enum_sources(Find,&lookup);if(!lookup.source)return false;QString type=item.kind==Kind::Compressor?QStringLiteral("compressor_filter"):QStringLiteral("limiter_filter");
    float currentVolume=api.source_get_volume(lookup.source);float tolerance=std::max(0.001f,std::abs(item.expectedVolume)*0.01f);if(!item.expectedFilterFingerprint.isEmpty()&&(FilterFingerprint(lookup.source)!=item.expectedFilterFingerprint||std::abs(currentVolume-item.expectedVolume)>tolerance)){api.source_release(lookup.source);return false;}if(HasFilter(lookup.source,type)||(item.kind==Kind::Compressor&&HasFilter(lookup.source,QStringLiteral("limiter_filter")))){api.source_release(lookup.source);return false;}
    QString base=item.kind==Kind::Compressor?T(COMPRESSOR_NAME):T(LIMITER_NAME),name=UniqueFilterName(lookup.source,base);if(name.isEmpty()){api.source_release(lookup.source);return false;}
    obs_data *settings=api.data_create();api.data_set_bool(settings,"sound_doctor_managed",true);api.data_set_int(settings,"sound_doctor_schema",1);api.data_set_string(settings,"sound_doctor_kind",item.kind==Kind::Compressor?"compressor":"limiter");api.data_set_double(settings,"threshold",item.threshold);
    if(item.kind==Kind::Compressor){api.data_set_double(settings,"ratio",item.ratio);api.data_set_int(settings,"attack_time",6);api.data_set_int(settings,"release_time",100);api.data_set_double(settings,"output_gain",0.0);api.data_set_string(settings,"sidechain_source","none");}else api.data_set_int(settings,"release_time",60);
    QByteArray typeUtf8=type.toUtf8(),nameUtf8=name.toUtf8();void *filter=api.source_create(typeUtf8.constData(),nameUtf8.constData(),settings,nullptr);api.data_release(settings);if(!filter){api.source_release(lookup.source);return false;}api.source_filter_add(lookup.source,filter);api.source_filter_set_order(lookup.source,filter,3);
    // Append after existing processing: the measured point matches the input
    // to the new filter. Compressor recommendations exclude existing limiters.
    api.source_release(filter);api.source_release(lookup.source);if(createdName)*createdName=name;return true;
}
static void RemoveApplied(const char *raw){
    QJsonDocument document=QJsonDocument::fromJson(QByteArray(raw?raw:""));if(!document.isArray())return;for(const QJsonValue &value:document.array()){QJsonObject object=value.toObject();Lookup lookup{object.value("uuid").toString()};api.enum_sources(Find,&lookup);if(!lookup.source)continue;QByteArray name=object.value("name").toString().toUtf8();void *filter=api.source_filter_by_name(lookup.source,name.constData());if(filter){obs_data *settings=api.source_settings(filter);bool managed=settings&&api.data_get_bool(settings,"sound_doctor_managed");if(settings)api.data_release(settings);if(managed)api.source_filter_remove(lookup.source,filter);api.source_release(filter);}api.source_release(lookup.source);}if(api.frontend_save)api.frontend_save();
}
static void RedoApplied(const char *raw){
    QJsonDocument document=QJsonDocument::fromJson(QByteArray(raw?raw:""));if(!document.isArray())return;for(const QJsonValue &value:document.array()){QJsonObject object=value.toObject();Recommendation item;item.uuid=object.value("uuid").toString();item.kind=object.value("kind").toString()=="compressor"?Kind::Compressor:Kind::Limiter;item.threshold=object.value("threshold").toDouble();item.ratio=object.value("ratio").toDouble();AddFilter(item);}if(api.frontend_save)api.frontend_save();
}
static void ApplySelected(const QStringList &ids){
    QJsonArray undoData,redoData;int applied=0,skipped=0;
    QStringList orderedIds;for(const Recommendation &item:recommendations)if(item.kind==Kind::Compressor&&ids.contains(item.id))orderedIds.push_back(item.id);for(const Recommendation &item:recommendations)if(item.kind==Kind::Limiter&&ids.contains(item.id))orderedIds.push_back(item.id);
    for(const QString &id:orderedIds){auto found=std::find_if(recommendations.begin(),recommendations.end(),[&](const Recommendation &item){return item.id==id;});if(found==recommendations.end()){++skipped;continue;}QString created;if(!AddFilter(*found,&created)){++skipped;continue;}++applied;undoData.append(QJsonObject{{"uuid",found->uuid},{"name",created}});redoData.append(QJsonObject{{"uuid",found->uuid},{"kind",found->kind==Kind::Compressor?"compressor":"limiter"},{"threshold",found->threshold},{"ratio",found->ratio}});Lookup updated{found->uuid};api.enum_sources(Find,&updated);if(updated.source){QString fingerprint=FilterFingerprint(updated.source);float volume=api.source_get_volume(updated.source);for(Recommendation &candidate:recommendations)if(candidate.uuid==found->uuid){candidate.expectedFilterFingerprint=fingerprint;candidate.expectedVolume=volume;}api.source_release(updated.source);}}
    if(applied){if(api.frontend_save)api.frontend_save();if(api.add_undo_redo){QByteArray undo=QJsonDocument(undoData).toJson(QJsonDocument::Compact),redo=QJsonDocument(redoData).toJson(QJsonDocument::Compact),label=T(APPLY_UNDO).toUtf8();api.add_undo_redo(label.constData(),RemoveApplied,RedoApplied,undo.constData(),redo.constData(),false);}}
    QString message=T(APPLY_SUMMARY).arg(applied);if(skipped)message+=QLatin1Char(' ')+T(APPLY_PARTIAL).arg(skipped);QMessageBox::information(obsMainWindow,T(TITLE),message);
}

static std::wstring ResultsHtml(){
    QString locale=QString::fromUtf8(api.get_locale?api.get_locale():"en-US");QString html=QStringLiteral("<!doctype html><html lang=\"%1\"><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width\"><title>Accessible Studio - %2</title><style>%3 body{line-height:1.55;margin:1.25rem;max-width:75rem}section{border-bottom:1px solid var(--obs-border);padding:.75rem 0}label{display:block;margin:.8rem 0;font-weight:600}button{font:inherit;padding:.5rem 1rem;background:var(--obs-button);color:var(--obs-button-text);border:1px solid var(--obs-border)}input{width:1.15rem;height:1.15rem;margin-right:.5rem}footer{padding:1rem 0}</style></head><body><main><h1 id=\"heading\" tabindex=\"-1\">%4</h1><p>%5</p>")
        .arg(QString::fromStdWString(HtmlEscape(locale.toStdWString())),QString::fromStdWString(HtmlEscape(T(TITLE).toStdWString())),QString::fromStdWString(DescriptionThemeCss()),QString::fromStdWString(HtmlEscape(T(RESULTS_HEADING).toStdWString())),QString::fromStdWString(HtmlEscape(T(RESULTS_INTRO).toStdWString())));
    for(const Recommendation &item:recommendations){html+=QStringLiteral("<section><h2>%1</h2><p>%2</p><p>%3</p><label><input type=\"checkbox\" value=\"%4\" aria-label=\"%5\">%6</label></section>").arg(QString::fromStdWString(HtmlEscape(item.sourceName.toStdWString())),QString::fromStdWString(HtmlEscape(item.reason.toStdWString())),QString::fromStdWString(HtmlEscape(item.settings.toStdWString())),item.id,QString::fromStdWString(HtmlEscape(T(APPLY_FOR).arg(item.sourceName).toStdWString())),QString::fromStdWString(HtmlEscape(T(APPLY_CHANGE).toStdWString())));}
    if(recommendations.empty())html+=QStringLiteral("<p>%1</p>").arg(QString::fromStdWString(HtmlEscape(T(NO_CHANGES).toStdWString())));
    if(!observations.empty()){html+=QStringLiteral("<section><h2>%1</h2>").arg(QString::fromStdWString(HtmlEscape(T(OBSERVATIONS).toStdWString())));for(const QString &note:observations)html+=QStringLiteral("<p>%1</p>").arg(QString::fromStdWString(HtmlEscape(note.toStdWString())));html+=QStringLiteral("</section>");}
    html+=QStringLiteral("<footer><button id=\"finish\" type=\"button\" aria-label=\"%1\">%2</button></footer></main><script>document.getElementById('finish').addEventListener('click',function(){this.disabled=true;const selected=Array.from(document.querySelectorAll('input:checked')).map(x=>x.value);window.chrome.webview.postMessage(JSON.stringify({type:'finish',selected}));});</script></body></html>").arg(QString::fromStdWString(HtmlEscape(T(FINISH_ACCESSIBLE).toStdWString())),QString::fromStdWString(HtmlEscape(T(FINISH).toStdWString())));return html.toStdWString();
}
static void Resize(){if(controller&&resultsWindow){RECT bounds{};GetClientRect(resultsWindow,&bounds);controller->put_Bounds(bounds);}}
static constexpr UINT WEBVIEW_FAILED=WM_APP+52;
static void InitializeWebView(HWND parent){
    wchar_t local[MAX_PATH]{};GetEnvironmentVariable(L"LOCALAPPDATA",local,MAX_PATH);std::wstring data=std::wstring(local)+L"\\AccessibleStudio\\WebView2";using Microsoft::WRL::Callback;++pendingWebViewInitializations;
    HRESULT result=CreateCoreWebView2EnvironmentWithOptions(nullptr,data.c_str(),nullptr,Callback<ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler>([parent](HRESULT status,ICoreWebView2Environment *environment)->HRESULT{
        if(shuttingDown||!IsWindow(parent)){--pendingWebViewInitializations;return E_ABORT;}if(FAILED(status)||!environment){PostMessage(parent,WEBVIEW_FAILED,0,0);--pendingWebViewInitializations;return status;}
        HRESULT created=environment->CreateCoreWebView2Controller(parent,Callback<ICoreWebView2CreateCoreWebView2ControllerCompletedHandler>([parent](HRESULT controllerStatus,ICoreWebView2Controller *createdController)->HRESULT{
            --pendingWebViewInitializations;if(shuttingDown||!IsWindow(parent))return E_ABORT;if(FAILED(controllerStatus)||!createdController){PostMessage(parent,WEBVIEW_FAILED,0,0);return controllerStatus;}controller=createdController;controller->put_IsVisible(FALSE);Microsoft::WRL::ComPtr<ICoreWebView2Controller2> controller2;if(SUCCEEDED(controller.As(&controller2))){QColor background=DescriptionPaletteColor(QPalette::Window);COREWEBVIEW2_COLOR color{static_cast<BYTE>(background.alpha()),static_cast<BYTE>(background.red()),static_cast<BYTE>(background.green()),static_cast<BYTE>(background.blue())};controller2->put_DefaultBackgroundColor(color);}controller->get_CoreWebView2(&webView);if(!webView){PostMessage(parent,WEBVIEW_FAILED,0,0);return E_FAIL;}Resize();Microsoft::WRL::ComPtr<ICoreWebView2Settings> settings;if(SUCCEEDED(webView->get_Settings(&settings))){settings->put_AreDefaultContextMenusEnabled(FALSE);settings->put_AreDevToolsEnabled(FALSE);settings->put_IsStatusBarEnabled(FALSE);settings->put_IsWebMessageEnabled(TRUE);}
            webView->add_WebMessageReceived(Callback<ICoreWebView2WebMessageReceivedEventHandler>([](ICoreWebView2*,ICoreWebView2WebMessageReceivedEventArgs *args)->HRESULT{LPWSTR raw=nullptr;if(SUCCEEDED(args->TryGetWebMessageAsString(&raw))&&raw){QJsonDocument document=QJsonDocument::fromJson(QString::fromWCharArray(raw).toUtf8());CoTaskMemFree(raw);if(document.isObject()&&document.object().value("type").toString()=="finish"){QStringList ids;for(const QJsonValue &value:document.object().value("selected").toArray())ids.push_back(value.toString());if(!applyingResults){applyingResults=true;const uint64_t generation=resultsGeneration;QMetaObject::invokeMethod(PluginEventTarget(),[ids,generation]{if(shuttingDown||generation!=resultsGeneration||!resultsWindow)return;if(!ids.isEmpty())ApplySelected(ids);if(resultsWindow&&generation==resultsGeneration)PostMessage(resultsWindow,WM_CLOSE,0,0);},Qt::QueuedConnection);}}}return S_OK;}).Get(),&messageToken);
            webView->add_NavigationCompleted(Callback<ICoreWebView2NavigationCompletedEventHandler>([](ICoreWebView2*,ICoreWebView2NavigationCompletedEventArgs *args)->HRESULT{BOOL success=FALSE;if(!args||FAILED(args->get_IsSuccess(&success))||!success){if(resultsWindow)PostMessage(resultsWindow,WEBVIEW_FAILED,0,0);return S_OK;}if(controller){controller->put_IsVisible(TRUE);if(ActivateKeyboardWindow(resultsWindow,resultsWindow)){SetFocus(resultsWindow);controller->MoveFocus(COREWEBVIEW2_MOVE_FOCUS_REASON_PROGRAMMATIC);if(webView)webView->ExecuteScript(L"document.getElementById('heading').focus();",nullptr);}}return S_OK;}).Get(),&navigationToken);
            controller->add_AcceleratorKeyPressed(Callback<ICoreWebView2AcceleratorKeyPressedEventHandler>([](ICoreWebView2Controller*,ICoreWebView2AcceleratorKeyPressedEventArgs *args)->HRESULT{UINT key=0;COREWEBVIEW2_KEY_EVENT_KIND kind{};if(SUCCEEDED(args->get_VirtualKey(&key))&&SUCCEEDED(args->get_KeyEventKind(&kind))&&key==VK_ESCAPE&&(kind==COREWEBVIEW2_KEY_EVENT_KIND_KEY_DOWN||kind==COREWEBVIEW2_KEY_EVENT_KIND_SYSTEM_KEY_DOWN)){args->put_Handled(TRUE);if(resultsWindow)PostMessage(resultsWindow,WM_CLOSE,0,0);}return S_OK;}).Get(),&acceleratorToken);
            std::wstring html=ResultsHtml();webView->NavigateToString(html.c_str());return S_OK;
        }).Get());if(FAILED(created)){PostMessage(parent,WEBVIEW_FAILED,0,0);--pendingWebViewInitializations;}return created;
    }).Get());if(FAILED(result)){PostMessage(parent,WEBVIEW_FAILED,0,0);--pendingWebViewInitializations;}
}
static LRESULT CALLBACK WindowProc(HWND window,UINT message,WPARAM wp,LPARAM lp){
    if(message==WM_CREATE){++resultsGeneration;applyingResults=false;InitializeWebView(window);return 0;}if(message==WM_SETFOCUS){if(controller)controller->MoveFocus(COREWEBVIEW2_MOVE_FOCUS_REASON_PROGRAMMATIC);return 0;}if(message==WM_ERASEBKGND){QColor background=DescriptionPaletteColor(QPalette::Window);HBRUSH brush=CreateSolidBrush(RGB(background.red(),background.green(),background.blue()));if(brush){RECT bounds{};GetClientRect(window,&bounds);FillRect(reinterpret_cast<HDC>(wp),&bounds,brush);DeleteObject(brush);return TRUE;}}if(message==WM_SIZE){Resize();return 0;}if(message==WM_KEYDOWN&&wp==VK_ESCAPE){PostMessage(window,WM_CLOSE,0,0);return 0;}if(message==WEBVIEW_FAILED){std::wstring failure=T(WEBVIEW_FAILURE).toStdWString(),title=(QStringLiteral("Accessible Studio - ")+T(TITLE)).toStdWString();MessageBox(window,failure.c_str(),title.c_str(),MB_OK|MB_ICONERROR);DestroyWindow(window);return 0;}
    if(message==WM_CLOSE){bool restore=GetAncestor(GetForegroundWindow(),GA_ROOT)==window;ShowWindow(window,SW_HIDE);DestroyWindow(window);if(restore&&obsMainWindow){HWND owner=api.main_hwnd?api.main_hwnd():nullptr;ActivateKeyboardWindow(owner);if(returnFocus)returnFocus->setFocus(Qt::OtherFocusReason);}return 0;}
    if(message==WM_DESTROY){if(webView){webView->remove_WebMessageReceived(messageToken);webView->remove_NavigationCompleted(navigationToken);}webView.Reset();if(controller){controller->remove_AcceleratorKeyPressed(acceleratorToken);controller->Close();controller.Reset();}resultsWindow=nullptr;resultsDeferred=false;recommendations.clear();observations.clear();returnFocus.clear();return 0;}return DefWindowProc(window,message,wp,lp);
}
static void ShowResults(){
    resultsDeferred=false;returnFocus=QApplication::focusWidget();WNDCLASSEX wc{sizeof(wc)};wc.lpfnWndProc=WindowProc;wc.hInstance=instance;wc.hCursor=LoadCursor(nullptr,IDC_ARROW);wc.hbrBackground=reinterpret_cast<HBRUSH>(COLOR_WINDOW+1);wc.lpszClassName=L"AccessibleStudioSoundDoctor";RegisterClassEx(&wc);
    std::wstring title=(QStringLiteral("Accessible Studio - ")+T(TITLE)).toStdWString();resultsWindow=CreateWindowEx(WS_EX_APPWINDOW|WS_EX_CONTROLPARENT,wc.lpszClassName,title.c_str(),WS_OVERLAPPEDWINDOW,CW_USEDEFAULT,CW_USEDEFAULT,820,620,nullptr,nullptr,instance,nullptr);if(!resultsWindow){QMessageBox::critical(obsMainWindow,T(TITLE),T(WINDOW_FAILURE));return;}ShowWindowPreservingState(resultsWindow);
}
static void Stop(bool showResults){
    if(showResults&&OutputsActive())return;if(!running.exchange(false))return;if(timer){timer->stop();delete timer.data();timer=nullptr;}for(auto &source:sources)Detach(*source);if(showResults){Analyze();ShowResults();}else{sources.clear();recommendations.clear();observations.clear();}waitingAnnouncementMade=false;
}
static void Tick(){if(!running.load())return;Refresh();if(promptOpen)return;if(elapsed.elapsed()<MONITOR_SECONDS*1000)return;if(OutputsActive()){if(!waitingAnnouncementMade){waitingAnnouncementMade=true;AnnounceAccessibility(T(WAITING_FOR_OUTPUTS));}return;}Stop(true);}
static void StartMonitoring(){
    sources.clear();recommendations.clear();observations.clear();waitingAnnouncementMade=false;running=true;elapsed.restart();Refresh();timer=new QTimer(PluginEventTarget());timer->setInterval(REFRESH_MS);QObject::connect(timer,&QTimer::timeout,PluginEventTarget(),Tick);timer->start();AnnounceAccessibility(T(RUNNING));
}
static bool InterruptWarningSuppressed(){
    config *cfg=api.global_config?api.global_config():nullptr;if(!cfg||!api.config_has_user_value(cfg,"AccessibleStudio","SoundDoctorInterruptWarningSuppressed"))return false;const char *value=api.config_get_string(cfg,"AccessibleStudio","SoundDoctorInterruptWarningSuppressed");return value&&(_stricmp(value,"true")==0||strcmp(value,"1")==0);
}
static bool SaveInterruptWarningSuppressed(){
    config *cfg=api.global_config?api.global_config():nullptr;if(!cfg)return false;api.config_set_string(cfg,"AccessibleStudio","SoundDoctorInterruptWarningSuppressed","true");return api.config_save_safe(cfg,"tmp",nullptr)==0;
}
static void InterruptMonitoring(bool suppressFutureWarning){
    Stop(false);AnnounceAccessibility(T(INTERRUPTED));if(suppressFutureWarning&&!SaveInterruptWarningSuppressed())QMessageBox::warning(obsMainWindow,T(TITLE),T(INTERRUPT_SAVE_FAILED));
}
static void PromptInterruption(){
    if(InterruptWarningSuppressed()){InterruptMonitoring(false);return;}promptOpen=true;QDialog dialog(obsMainWindow);dialog.setWindowTitle(QStringLiteral("Accessible Studio - ")+T(TITLE));dialog.setModal(true);auto *layout=new QVBoxLayout(&dialog);auto *message=new QLabel(T(INTERRUPT_QUESTION),&dialog);message->setWordWrap(true);message->setAccessibleName(T(INTERRUPT_QUESTION));layout->addWidget(message);auto *suppress=new QCheckBox(T(DONT_SHOW_INTERRUPT),&dialog);layout->addWidget(suppress);auto *buttons=new QDialogButtonBox(QDialogButtonBox::Yes|QDialogButtonBox::No,&dialog);QPushButton *yes=buttons->button(QDialogButtonBox::Yes),*no=buttons->button(QDialogButtonBox::No);yes->setDefault(true);yes->setAutoDefault(true);QObject::connect(buttons,&QDialogButtonBox::accepted,&dialog,&QDialog::accept);QObject::connect(buttons,&QDialogButtonBox::rejected,&dialog,&QDialog::reject);layout->addWidget(buttons);QWidget::setTabOrder(suppress,yes);QWidget::setTabOrder(yes,no);yes->setFocus(Qt::OtherFocusReason);int result=dialog.exec();promptOpen=false;if(result==QDialog::Accepted)InterruptMonitoring(suppress->isChecked());else if(PluginEventTarget())QTimer::singleShot(0,PluginEventTarget(),[]{Tick();});
}
static void Prompt(){
    if(promptOpen)return;if(resultsWindow){if(resultsDeferred||OutputsActive()){AnnounceAccessibility(T(WAITING_FOR_OUTPUTS));return;}ActivateKeyboardWindow(resultsWindow,resultsWindow);SetFocus(resultsWindow);if(controller)controller->MoveFocus(COREWEBVIEW2_MOVE_FOCUS_REASON_PROGRAMMATIC);return;}if(running.load()){PromptInterruption();return;}if(audibleMeterActive.load()){QMessageBox::information(obsMainWindow,T(TITLE),T(AUDIBLE_ACTIVE));return;}promptOpen=true;bool live=OutputsActive();QString instructions=T(live?INTRO_LIVE:INTRO);
    QDialog dialog(obsMainWindow);dialog.setWindowTitle(QStringLiteral("Accessible Studio - ")+T(TITLE));dialog.setModal(true);auto *layout=new QVBoxLayout(&dialog);auto *message=new QLabel(instructions,&dialog);message->setWordWrap(true);message->setAccessibleName(instructions);layout->addWidget(message);auto *buttons=new QDialogButtonBox(&dialog);QPushButton *start=buttons->addButton(T(START),QDialogButtonBox::AcceptRole);QPushButton *later=buttons->addButton(T(NOT_NOW),QDialogButtonBox::RejectRole);start->setDefault(true);start->setAutoDefault(true);QObject::connect(buttons,&QDialogButtonBox::accepted,&dialog,&QDialog::accept);QObject::connect(buttons,&QDialogButtonBox::rejected,&dialog,&QDialog::reject);layout->addWidget(buttons);QWidget::setTabOrder(start,later);dialog.resize(650,live?340:260);start->setFocus(Qt::OtherFocusReason);int result=dialog.exec();promptOpen=false;if(result==QDialog::Accepted)StartMonitoring();
}
}

static double SoundDoctorMinimumCompressionSpreadDb(){return SoundDoctor::MinimumCompressionSpreadDb();}
static double SoundDoctorMaximumCompressionRatio(){return SoundDoctor::MaximumCompressionRatio();}
static bool SoundDoctorLimiterAllActiveSources(){return SoundDoctor::LimiterAllActiveSources();}
static double SoundDoctorLimiterThresholdDb(){return SoundDoctor::LimiterThresholdDb();}
static bool SaveSoundDoctorSettings(double spreadDb,double maximumRatio,bool allActiveSources,double limiterThresholdDb){
    if(!std::isfinite(spreadDb)||spreadDb<6.0||spreadDb>15.0||!std::isfinite(maximumRatio)||maximumRatio<2.5||maximumRatio>3.5||!std::isfinite(limiterThresholdDb)||limiterThresholdDb<-12.0||limiterThresholdDb>-1.0)return false;
    config *cfg=api.global_config?api.global_config():nullptr;if(!cfg)return false;api.config_set_double(cfg,"AccessibleStudio","SoundDoctorMinimumCompressionSpreadDb",spreadDb);api.config_set_double(cfg,"AccessibleStudio","SoundDoctorMaximumCompressionRatio",maximumRatio);api.config_set_double(cfg,"AccessibleStudio","SoundDoctorLimiterAllActiveSources",allActiveSources?1.0:0.0);api.config_set_double(cfg,"AccessibleStudio","SoundDoctorLimiterThresholdDb",limiterThresholdDb);return api.config_save_safe(cfg,"tmp",nullptr)==0;
}

static std::string SoundDoctorCommandLabel(){QByteArray text=SoundDoctor::T(SoundDoctor::COMMAND).toUtf8();return {text.constData(),size_t(text.size())};}
static bool SoundDoctorIsRunning(){return SoundDoctor::running.load();}
static QString SoundDoctorBusyMessage(){return SoundDoctor::T(SoundDoctor::METER_BLOCKED);}
static void ActivateSoundDoctor(){SoundDoctor::Prompt();}
static void SoundDoctorHotkey(void*,hotkey_id,obs_hotkey*,bool pressed){if(pressed&&PluginEventTarget())QMetaObject::invokeMethod(PluginEventTarget(),[]{ActivateSoundDoctor();},Qt::QueuedConnection);}
static void ShutdownSoundDoctor(){SoundDoctor::Stop(false);if(SoundDoctor::resultsWindow)DestroyWindow(SoundDoctor::resultsWindow);QElapsedTimer wait;wait.start();while(SoundDoctor::pendingWebViewInitializations.load()>0&&wait.elapsed()<10000){QCoreApplication::processEvents(QEventLoop::AllEvents,50);MsgWaitForMultipleObjects(0,nullptr,FALSE,10,QS_ALLINPUT);}}
static void HandleSoundDoctorFrontendEvent(int event){
    constexpr int SD_STREAMING_STARTING=0,SD_STREAMING_STARTED=1,SD_STREAMING_STOPPED=3,SD_RECORDING_STARTING=4,SD_RECORDING_STARTED=5,SD_RECORDING_STOPPED=7,SD_COLLECTION_CHANGED=13,SD_PROFILE_CHANGED=15,SD_EXIT=17,SD_COLLECTION_CLEANUP=25,SD_COLLECTION_CHANGING=35;
    if(event==SD_EXIT){ShutdownSoundDoctor();return;}
    if((event==SD_STREAMING_STARTING||event==SD_STREAMING_STARTED||event==SD_RECORDING_STARTING||event==SD_RECORDING_STARTED)&&SoundDoctor::resultsWindow&&IsWindowVisible(SoundDoctor::resultsWindow)){SoundDoctor::resultsDeferred=true;ShowWindow(SoundDoctor::resultsWindow,SW_HIDE);HWND owner=api.main_hwnd?api.main_hwnd():nullptr;ActivateKeyboardWindow(owner);}
    if(event==SD_STREAMING_STOPPED||event==SD_RECORDING_STOPPED){if(SoundDoctorIsRunning()&&PluginEventTarget())QTimer::singleShot(0,PluginEventTarget(),[]{SoundDoctor::Tick();});if(SoundDoctor::resultsDeferred&&!SoundDoctor::OutputsActive()&&SoundDoctor::resultsWindow){SoundDoctor::resultsDeferred=false;ShowWindowPreservingState(SoundDoctor::resultsWindow);ActivateKeyboardWindow(SoundDoctor::resultsWindow,SoundDoctor::resultsWindow);SetFocus(SoundDoctor::resultsWindow);if(SoundDoctor::controller)SoundDoctor::controller->MoveFocus(COREWEBVIEW2_MOVE_FOCUS_REASON_PROGRAMMATIC);}}
    if(event==SD_COLLECTION_CHANGED||event==SD_PROFILE_CHANGED||event==SD_COLLECTION_CLEANUP||event==SD_COLLECTION_CHANGING){bool wasRunning=SoundDoctorIsRunning();if(wasRunning)SoundDoctor::Stop(false);if(SoundDoctor::resultsWindow)DestroyWindow(SoundDoctor::resultsWindow);if(wasRunning)AnnounceAccessibility(SoundDoctor::T(SoundDoctor::CANCELLED));}
}
static void ApplySoundDoctorTheme(){
    if(SoundDoctor::controller){Microsoft::WRL::ComPtr<ICoreWebView2Controller2> controller2;if(SUCCEEDED(SoundDoctor::controller.As(&controller2))){QColor background=DescriptionPaletteColor(QPalette::Window);COREWEBVIEW2_COLOR color{static_cast<BYTE>(background.alpha()),static_cast<BYTE>(background.red()),static_cast<BYTE>(background.green()),static_cast<BYTE>(background.blue())};controller2->put_DefaultBackgroundColor(color);}}
    if(!SoundDoctor::webView)return;QJsonArray value{QString::fromStdWString(DescriptionThemeDeclarations())};QString script=QStringLiteral("document.documentElement.style.cssText=")+QString::fromUtf8(QJsonDocument(value).toJson(QJsonDocument::Compact))+QStringLiteral("[0];");SoundDoctor::webView->ExecuteScript(script.toStdWString().c_str(),nullptr);
}
